apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secret
spec:
    secretTemplates:
        - name: cloudflared-secret
          stringData:
            credentials.json: ENC[AES256_GCM,data:GZBZj/IPPU2PD2Gq7rTI7iHeA++LRc3jRADsU3pKvfXzBTadfpHWyRhwc9d8n1St8CKt4Fw06BF4KjcF5t4LNDL88LFBuOO9RqKDVFHp9jP4wmSCpFBP0aQ9zKYaX04g+ftWEEfjKY+dbJ5qoTXrrth6NluS+dJtISods1bEJXtFmg3RZ7W9WN/Yf5XJ7UkMNcqbQIMW+TSKncCR7OxvJSqmuZE/jV8ML11gYMXc1A==,iv:jRBhsmNg8qteqRNStElW84Se23wh1ygX+HW3Phgb6TM=,tag:qmtYPzo/FWGuY5b541aKqw==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOVFCZ3U4S0dVQmdKNmRZ
            cXR1SzdVREM0TmRXaTgyMmJMZlowajVnZ3hjCmFQY2h6V2ZxTGlZVjh6YzE5dzcr
            UXpYeUx5c2JnNzhIcHEwZVR1bzg3blUKLS0tIE9wd1Fxdno2WFl3c24wR2RGYlF0
            enNMZmhTaFNnMlR6eEhmVm5BK2dlL3MKsZauSjWQBYhxVgeYtqd6aLRWd143LgFS
            wx6awJo1xjzvnpwE6lLmEWWquWpUjF13rHUXYGzTFs0oa2FlokefvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN3dGWThjS3FhajYvTEtF
            ekNNNm5mL25rNFRlU3o2bDRXdDE4VUhyOFU0CkptNWpGSW5MQTNCRmNYck1JdGU2
            WVZYa0w2QVpkT3JuQlcwTE5waE55d3MKLS0tIEIwczNrbGFkdjVxVzJiWWNUUHR1
            eWtzRHgzOEtxbXVhMmdJUE5iclVwOVUK9MSESY5h3P97VDMw38sNN56BCmYaluYx
            CpJ8054E3JvAfMGZjZYLSXYeXTDiCDW8U4gEUdxWI3gPqbycfJmN0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T3lEMVg2MVpxWU8rbU9F
            NWNqZFVTVVpGbm4vSEh3Q3NYYlB4VTk4aUMwCkVqL0IxblBYbTVzTUg4T3JPWnd5
            WkhIZE0wSUhPTno1czYxSTVEL2ZHR1UKLS0tIDV1SzYycHVHb2kzZTNXeVJpSFk3
            RGdYMHRrUXRxR0puc04wUXlwdWhLQ00K71WjVCHR8H0vRNPFp9X+tR6lYRpv79sM
            RbKEIXHLYqkeURfWcBFcKVdfzAaFn/WcFYo6L1eFmeXjRYWcfx/KXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWXlvb3FlVzJHc2RkNFYr
            eDBETHhEa0xwODFIdGY0OS9XMGEzb1phOG1vCi9tZlIyVVl4Nzh5WnJBTHJCcDVE
            YmhCU1NLTlA3dm5wMmNvbkx4bEZBNnMKLS0tIG1lRFVKV1lFbnErMWcxcjBkT3BP
            QVZXaVg2WTBRaktucjczVzBWNlBXL1EK7rNwApUm08nFNe65BdmhH1tivzv58HV/
            2GRYvxacnD2SPKGX9utNkj+44UdJ/WaSDnQ4k/AbYw3CmsLV2s+Ldg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMnlLb2lzanpTR3Y0RXM4
            NytqQTdpZTdUa1l0K05COGk5ck9CeGN3ZXo4CmdlVWJmNTk4WTFJdkZhc1dZWnF2
            NFhNK3NWSTZwSys2eUtDcGJUSkh0dFEKLS0tIFI0eXdUS25GNGJOSXlOWjZ6Q1Vw
            bjFPbUVnTlV2R2VjTkRUREJVM2NKTzgKmjh/aE2kfa33jNgs9mRXXZP8AbRiKpHS
            //q+ee2jhc3eoNKZBA0ZEFZwTfs1T24MtvQ0ZdpQTamFyWHnOcMIZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWEdlQXl0Z2ZKeko4RXJQ
            UXV2N1R0ZitxajZLWjc1MHNJckFTcEs3OEdvCkJZRVNKMmVTYjNjcVJRU1VCdXc2
            ZFhDN1MySDVRM3NhNk5qczhzcXZsRUUKLS0tIGtPOWNWWjNMeTZQZy9GVlNsOGd6
            ckNORlVJV3ZFbnowdUkxa1I5Vm5CSFkKKDe6ZW1fLpqDxKqjFR+p06gwsjflsllp
            lGUpRrPPJQa9UTqPn2lf2rCrJH+sWEIzeFea4RfFuMFTPs2NfK3cQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Umc4TTNNQ3BTaURsQWwy
            UDhoSWZpeTdSU0p4TDZaVTBISkhhTDFHdUVFClRDQk1ySEFhRjFWR2twZ3FkdUF4
            U1BNamJkZllzQXpJOEo4a0E3dUYzVUkKLS0tIE81SHlJaDlVZjRFcDc0MTBscld4
            MitncTVuMEt5aWhtd0FYOFVUc2FkMzQK1HwvQFWx4Y85H1CSSjTQ4MkSfbGZSBbA
            /ovyg4xns7QIs2oxH7c3+ugEBYEs6v5WJsatxwBVahOD8onaQ9p0MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:47:31Z"
    mac: ENC[AES256_GCM,data:H+3f0WjlMEtpqYaqayQFh/0XXij/bVqHstXLVWBtE9UiVlnd2ktmqpioxNISTWmQ5kqSqz+a56+mPaBrnnGLvgtpqGNhujAQp7TPHtTiC1wYdHKVyGe+AxQpDQ1QmRClNbOQ+BMGmsRVlsi3lIUjnbKIC2fp1BRVtDW1vL2PHpo=,iv:whCEJvH/C5xiy7uoBmWsoJ+sYevhW5qgGC75BrHpAl8=,tag:DFEhQyTFjbGNfKLxhHkuNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
