apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    credentials.json: ENC[AES256_GCM,data:t66qC7Oviiuk1S9cTaxdXdDULAj760aNrpDBd9+UkfTqgOy5Qw5HWJsH4E1kzC/Enhq8vn+yndkl09kRDfRcrWrRPcPqFFTbcSL4vp1QcMGTR7ZuPAOzBrTXdTFxmcsmMA9i+vUV2VrKKUrDKvO98nQm51NmwEygNV3pBclJGIwqXC5LIFNNnnH0PKK6a3qX/Bgmzm1MMBwRdRif3yck/1em/JW1C2QoNgiqQcMo/JZFUdliSJnB5I6QIWNanBhoHG8WEdKqFOLm1Vn7Mlx64LwZBeDGc3fJvs/GvUUCEXaop9r6DdBF4VB9N+5stiZw4n05cAst5uwH+tu8xp9f7NroP67UC8aRFkKdvYgZoQUWgtEG25sJg8twt3/UD6cDwxiZJg==,iv:VJZkiRuHRW9JPFCv4RtMsndh3ARIgn6CWDydXDRee5k=,tag:/6MptPk1NS+udpSdjfRSXw==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT3pxMHJkbkxlZjJzRVht
            ZzRqTEo4UU83WjlpNVhNU0tiaUsvSlRpWEJFCnFpQXlHaWRyYmxiMVJIamFQZU4v
            amNNZEpFUDB1RHc0V0piMXY4UU9kYzgKLS0tIE1rZ2FKVkJwQWl6bzJreGVJSU8x
            NjEwM3RmVFZVNlp1SEw1MkR6QTBzc1EKxdvs3IGKY/ZZxpniufyCBFrXWEiGAhAV
            MpiQKwv5gFN3j36I5IzHyCzipGfelVly2E4FizQ73oBbUoFpUarMXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bU5mczUvb3lrT1EyZ1A0
            dG82YlVjdzZMSENaamoxdDc2TVdlRGtTaGh3CnNMaXpOdW9OY29HNUw0V1BHS0FO
            dkF4RytjdS9Pcyt4WFFPOENveWdib0kKLS0tIG8rTm1iK2sra2VWL0YxT1prQTJE
            NTNidmxIcFdHSjNCSUhibXRMOTVLeEkKutr+v6rPmdQJodpXX41Y7FcoG1Hts+CJ
            +gQ4ma8hyLQCFuB/Dr+/YE6pw4VbyIQAkFRQi6zalfEjX7sIpLaAUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbkduclJKVXQ0TUlyZncv
            bTBxYTdITlRjUnJVR0NPcnByZEgxa252NmxvCk9aUnB3M1oyODNJK0VRVlZCbFNS
            Wlc2WmFQNTQrTmJOMU9KUFZ5NUdPMGMKLS0tIHlQU3NyOSs0LzBqdmppay9YNDNU
            WnNPSVFaNkF4NVRNZnROWEFJUlZsNnMKBQft0qmq8OtAEinC2Lw/GmCy4xhUjqh8
            vQWsuVDeLa4n9e2K/Dt7mtWtPEG6SMeFYyMvhFzqTaKTBTe3u0/lbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra0VmMTVxcXpBZFdJWTBR
            VGtpNHI0b2tzMEtiT3VzVUtZL09FRHRjU3lVCkpNNjZFZE1MbW1sWWlQQjQ4TUF4
            encySVhDRG5sN2QxcUpkcmlTamhhV0UKLS0tIEM2Q3Zna3lyZWFNQ3UrbTk0WWFx
            QW0zTDMrbHRJWlFxK2xFQktlcjlBeTAKI1OidPNHEyJY0eqaiI1XboZ/08CF/ZV4
            +5UIBwlFEO5gmqX1zKIVHmnLVdZfypknZMlrFHuayKDW9vkTn0KOgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYlpKc1VCczlRK041bmw0
            dm5RdHVIa2N4NnljUlgrZzJDdTUyS0JuL3pvCkZ5ZkpuSzlrQzB5eU4wUk1sQ0Ro
            WGJIVEwxNGVITk1HNktwblJDL1liYzAKLS0tIFJwV2IwV1pPK3pBcUZNam8yQ2VW
            MlMyUlVhS3RrMGNVVHhacWJJUFozaWcK39tvz5iYNMGiewfEvH0vFcADQGr+2Qfx
            aUYim2/22rqn1IV9TEqA2IRwt0qLBV0spVJiMQwDn4vezIaSi63KTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMWJhckdEQWxvYm5IZktG
            eVF2b3NzSmlDbW5ZQ1QwM0UrQUMvN0VCaWpNCks1OWZaU0VNeW45RzhkZTZmSGkw
            UlVtM1J4TWtzNjhXV1ozQkZneXA2NjgKLS0tIHcwdU0ra3I5ZndvNlFtNm9YN2FP
            bkJRZGtiUGh6U2RQWXJEc0FpVjZzNmMKqFaiKGYHFMhSaTLw7zNyvKxIfbMDQdyY
            sTlyTm0EFk1md0XHxZynSVfRWUHT6dNj1NSAmAS1lNqxkoOgQ4TH6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:05:49Z"
    mac: ENC[AES256_GCM,data:hNlb6/ng0X+5jdbLHMWMSJXfcI5jdmy0SueD57qzp9kF3ejIZpmOFdL3YU8I7naqy+g6CteWqf5+JnDieotfWLg+eAO468/Eqv9x8Wtq2e8x9fbFQpNq6793PHXq6M75G9El2CUv3AMPTb1axco7RnXAYUPT+Ad7Jjw8UCmaJxs=,iv:fMeuizwO+iZEpxKYKlgh8m1ngX03H55Rw9TSTweC0ws=,tag:+py0hZphhiW9YeOvovU2Kw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
