apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    credentials.json: ENC[AES256_GCM,data:Qb21tgZEwajVqZpIuI3ubUHMbGbW10HDiW2dmUjTay8WLzxx8Q1Gt4A4zPMTrm5pdRCVedIfGwDkWHBEsNtKewJJmO1+GMwhSc9IUG3EBjuTLiR/i3puT9BSrS6ArGFt8crYH3oZkgTjoc8xcjJ68N0ZEfaxnuy03PSr1Dmq9j8gvwG6yEoxsMOiplz3dD6ZhP0GE6ohMGEyopRmkGiieManP0x2EnhybiIMN44uqNQlb/UvuZBffZokG4LvYpbEf3HJNsM+1MhyLgZ7nV6zktotSo8WOL4YLR3j4ZKWPL1QfTpHmr7iStrBZM3OXxHW/99xVlg9joExIW3gxZvBile6qF21VbkRriUo4bMj4I/h2HHrUUYudZ5fTXVMUnE1p0NYF82MRCjCQdeVTiZBeEbYJQ1isN+OQ5da,iv:GgIk2YEdU6Bw2WiehD+1YzFOACOl/8jjAn0LPVrSHUI=,tag:l2EaHTN3G4GXYuEe162haQ==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArT3pxMHJkbkxlZjJzRVht
            ZzRqTEo4UU83WjlpNVhNU0tiaUsvSlRpWEJFCnFpQXlHaWRyYmxiMVJIamFQZU4v
            amNNZEpFUDB1RHc0V0piMXY4UU9kYzgKLS0tIE1rZ2FKVkJwQWl6bzJreGVJSU8x
            NjEwM3RmVFZVNlp1SEw1MkR6QTBzc1EKxdvs3IGKY/ZZxpniufyCBFrXWEiGAhAV
            MpiQKwv5gFN3j36I5IzHyCzipGfelVly2E4FizQ73oBbUoFpUarMXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bU5mczUvb3lrT1EyZ1A0
            dG82YlVjdzZMSENaamoxdDc2TVdlRGtTaGh3CnNMaXpOdW9OY29HNUw0V1BHS0FO
            dkF4RytjdS9Pcyt4WFFPOENveWdib0kKLS0tIG8rTm1iK2sra2VWL0YxT1prQTJE
            NTNidmxIcFdHSjNCSUhibXRMOTVLeEkKutr+v6rPmdQJodpXX41Y7FcoG1Hts+CJ
            +gQ4ma8hyLQCFuB/Dr+/YE6pw4VbyIQAkFRQi6zalfEjX7sIpLaAUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbkduclJKVXQ0TUlyZncv
            bTBxYTdITlRjUnJVR0NPcnByZEgxa252NmxvCk9aUnB3M1oyODNJK0VRVlZCbFNS
            Wlc2WmFQNTQrTmJOMU9KUFZ5NUdPMGMKLS0tIHlQU3NyOSs0LzBqdmppay9YNDNU
            WnNPSVFaNkF4NVRNZnROWEFJUlZsNnMKBQft0qmq8OtAEinC2Lw/GmCy4xhUjqh8
            vQWsuVDeLa4n9e2K/Dt7mtWtPEG6SMeFYyMvhFzqTaKTBTe3u0/lbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAra0VmMTVxcXpBZFdJWTBR
            VGtpNHI0b2tzMEtiT3VzVUtZL09FRHRjU3lVCkpNNjZFZE1MbW1sWWlQQjQ4TUF4
            encySVhDRG5sN2QxcUpkcmlTamhhV0UKLS0tIEM2Q3Zna3lyZWFNQ3UrbTk0WWFx
            QW0zTDMrbHRJWlFxK2xFQktlcjlBeTAKI1OidPNHEyJY0eqaiI1XboZ/08CF/ZV4
            +5UIBwlFEO5gmqX1zKIVHmnLVdZfypknZMlrFHuayKDW9vkTn0KOgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYlpKc1VCczlRK041bmw0
            dm5RdHVIa2N4NnljUlgrZzJDdTUyS0JuL3pvCkZ5ZkpuSzlrQzB5eU4wUk1sQ0Ro
            WGJIVEwxNGVITk1HNktwblJDL1liYzAKLS0tIFJwV2IwV1pPK3pBcUZNam8yQ2VW
            MlMyUlVhS3RrMGNVVHhacWJJUFozaWcK39tvz5iYNMGiewfEvH0vFcADQGr+2Qfx
            aUYim2/22rqn1IV9TEqA2IRwt0qLBV0spVJiMQwDn4vezIaSi63KTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMWJhckdEQWxvYm5IZktG
            eVF2b3NzSmlDbW5ZQ1QwM0UrQUMvN0VCaWpNCks1OWZaU0VNeW45RzhkZTZmSGkw
            UlVtM1J4TWtzNjhXV1ozQkZneXA2NjgKLS0tIHcwdU0ra3I5ZndvNlFtNm9YN2FP
            bkJRZGtiUGh6U2RQWXJEc0FpVjZzNmMKqFaiKGYHFMhSaTLw7zNyvKxIfbMDQdyY
            sTlyTm0EFk1md0XHxZynSVfRWUHT6dNj1NSAmAS1lNqxkoOgQ4TH6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:09:59Z"
    mac: ENC[AES256_GCM,data:mEz2imzvfnGBHlgAbO80xMkPtlqYzzS2EcO8sPPFBTtwmw5b10+JE1DWiTX41UZKQiiA22YM8V0Owcb4GTLud1E1cyYCTbWE4enzLJVR26erIubruumk+a8qk8E/iOozQHzCB1+IV00ueNZ1IOG9U0i9aRNr/abR7Gikq/22MWk=,iv:CBbl5oVqLS5aihd5WMUPQQ2fwDsdDD8yiOxcU5/m1kQ=,tag:orooepT1aY6CRDmgss03eA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
