apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-secret
spec:
    secretTemplates:
        - name: cloudflared-secret
          stringData:
            credentials.json: ENC[AES256_GCM,data:GZBZj/IPPU2PD2Gq7rTI7iHeA++LRc3jRADsU3pKvfXzBTadfpHWyRhwc9d8n1St8CKt4Fw06BF4KjcF5t4LNDL88LFBuOO9RqKDVFHp9jP4wmSCpFBP0aQ9zKYaX04g+ftWEEfjKY+dbJ5qoTXrrth6NluS+dJtISods1bEJXtFmg3RZ7W9WN/Yf5XJ7UkMNcqbQIMW+TSKncCR7OxvJSqmuZE/jV8ML11gYMXc1A==,iv:jRBhsmNg8qteqRNStElW84Se23wh1ygX+HW3Phgb6TM=,tag:qmtYPzo/FWGuY5b541aKqw==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUzMzQkkyS2RuQUNLaDFx
            YU1wVkYwbm0xcXBzbDcvbkJMNVRXU0RSSUJvCk9mZGMxMi9oeTU4b3VtSGYrZkpS
            NnpOdXpKV0ZpV1U0UDF6b2c5ODZsY2sKLS0tIHFpbVNqWkFpUmVWTkhZYnV6Qngv
            L3VNRlcycy8wT3hoT2puak4ybHdvMUEKkCTt2in0hdGc5EMl+cmpNgynAQAmIKAn
            +rW45C/LCV3i1clp2s4GW0UoxkcJyrj8t+X3PYxz+P6C38TnReop5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKY0I5MmJiYmx6eTNQYnJZ
            dHhSaUtENSs5YndWdUllOXVTVEp5RDlDL0c4CmVLeU1ndmdkN3d6cUdDWEhwVTJq
            aExxY2N3bXlaOWJhYzFJcDlBbHhMcW8KLS0tIFRjVEhNQ0pzUjlsZmE2eHVxSmM3
            ODVFMkRyVlVSNVc5QnBsTVBTMXJHMGcKIjpubhkiI7PJ+ssR4alPUOa5+Nr6+D6P
            sXRDlhtNatRth02Wa38VP3DsWrNt4yJi4SKsubiE7RRnS0XrSD1pdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOWhrZHB2bzE0QXNjLzZx
            T1NkYmRkUEdpTDJBdUg1aVczMUpCbWd5MFdFCmp4K1BxRzg2UG1nQjFNT2JsSmNk
            bWRoTHVhUjZmV0pYK3dua0xtNjd1M2sKLS0tIDZHeHlaMFc0Z205Ky9NZVBaUm04
            VlFGKzhUU2J3end5MjRuajhoS1l3TWsKZKRp0RM5E6jA24PjGDprn7kHOkAEvWAD
            Otg5nvnx0r/uq5xpVVhwWmBz7JCHY/vkbsao2rlBYiWLtvnTzg2hQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdGhGaXNLWFQ3MEhMTWsr
            OGJkUkNBQjBRVWhUYzBieGxzZWYvOXRhM2xVClJIaTI5T1BNaHZEOUpyWnhJOHRY
            c2s1ZVdlTXR2NjN2azhDZHh5eElRdFEKLS0tIG9JbC8ydXZRVWFLcUh6S3hvaDQy
            VW02SG9nZzc1WEJMM2xFWTZya0NqKzAKEcGcgpTWIfaReSl/lS+HCMtk+jwagi2G
            XpZ0zOZqEqee/CfmI/nZc3OUpQ+9ilB+7cbkXxIrhJvVVwOtEqrHaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNEJaZ1UzblhlMGQvb25B
            RlVTZjFydVMwSE5kbklmNjV5UFVDMHpmcW5JClFrbncwVTlWNTZQbHdzUkg1MFNm
            YStqL2tDKzR1amhPY3FOVEZadVUxU1UKLS0tIHZBa3laWFZnbHA2cE0rMkREWk5W
            Tk9SaG1sdUhDSjlWd2pxaTFoeVhadGMK9sYN8O/BJubbKosVcGAWbhCu1Mn/9ygg
            BqXpWGxhNzVWhpgCRlRWM9nEjQ05IaJ08y6/OVhXL105vVCApKZ5Kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Ulordld1ekpwMlhGL2p0
            SXdSS2RYSEdSTzBhc2FSRE9TNTRnUkNvUmdVCjBUNXpLVDliRzQ2WHdhMkxwZEM2
            REtjUFFIM0FmU3psWjNEN0NFQnhyU1EKLS0tIFA2Nnc4RmJuUzd5a255Zm5ScGFR
            S2cyRFdPMkFsdzNoQmxZbUpoamdwY3cKupJuv6emeVZhpo5foOcAwPa+JFPRr/7T
            Tx5BOlw/oKS6xP/b8YZXv9OgJey89kU9vG5a9nic9TytNmnOlePsMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T04:47:31Z"
    mac: ENC[AES256_GCM,data:H+3f0WjlMEtpqYaqayQFh/0XXij/bVqHstXLVWBtE9UiVlnd2ktmqpioxNISTWmQ5kqSqz+a56+mPaBrnnGLvgtpqGNhujAQp7TPHtTiC1wYdHKVyGe+AxQpDQ1QmRClNbOQ+BMGmsRVlsi3lIUjnbKIC2fp1BRVtDW1vL2PHpo=,iv:whCEJvH/C5xiy7uoBmWsoJ+sYevhW5qgGC75BrHpAl8=,tag:DFEhQyTFjbGNfKLxhHkuNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
