apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-config
spec:
    secretTemplates:
        - name: adguard-config
          stringData:
            url: ENC[AES256_GCM,data:wM4U6uS9kLLdoF5Y1y0Opc++uKxY9XOXj8wvG96X41kRibua9MnZL/5wUm2HiGvzf/LFp1BZTvMjnmJmdg==,iv:yAp2q6c4Ek814Rz+PmMpuW5M+00f3+XyRQ+WdpeU+WA=,tag:8zIpRZ5JjjVn/oijtrTvuA==,type:str]
            user: ENC[AES256_GCM,data:YDgg0c4=,iv:RrlAbJVoc9wjtyJNcBGsI7uK+2oSNIXzVCuXq0DgK28=,tag:nTqQ5AXYT03nM1xPvZF9yA==,type:str]
            password: ENC[AES256_GCM,data:fPQndyr0JoAFNkCJMMQ1+NoT7w==,iv:kkuXJljhlHCjzwRBX+nrzhFk+q1X/AZuv3LrKsQUoQ8=,tag:D+cE84y5jmqXvETTss52tA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Ymh2WjFnL2NJbEtvcitO
            YXV3L0NjZ0FLYWZVMnJ0OTcrRkpIWHBGazFJCjRvREVDaWFSWm5USU9rWitCeSsr
            OU5vdE5Ld3NyelNJcXlZd0xZREdCeGsKLS0tIHF6Ti8zNWdCbzBtQ0VNMlZueDdY
            dDRuTlVBbHk4M3EvNURLbWtjQ2ZGQW8KpcD+eOGiEhoozedArx70K0SMimW6EELK
            melTqApJCCkkZ1kpde7aLhl+uFyXP3JvMMPJ+Dh66GU0xQt3U2kX+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd2JDOW9sNkZJRnZ2TTVh
            Rm5hSUF1UFRHQ0M3K1pEZmJ3eFV6VUZEdVNRCk9VaEJuU3M3WVdyZXpCUmZoV28y
            aGIyM1RoSGhub0NkcERiWXpvZVlnazQKLS0tIGhQQjBOWjhCRjlVbFFCejBnYzk2
            SCtXZURuQ1NORHNxT1FFVWR6NjBUREUKsx1MLld2SV2DWJi0DRc365BPsLSbyTtg
            zZowd+NgKdX8vBayyGma0wIOmwUHTNzfAfhApv0eYly/xDjhtxqMqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUXhncDl6UjA4WDhXZGc2
            VDlpSEtaaVk0S2xGTndUVmtHYThBQUorR1g0CkRRYTZNaGJjeHViVURCSTFMcTZR
            VWRYWmxSWnMrNG54d1dXMFRaNVVUZk0KLS0tIGc0TjFoWkxMRlJaUVpjVzV0L25E
            OVIzYjNoRk9xR3MyV1pPN01lWERSMGcKbIN7ndxsYLI2VP1rDfh3dV164B/P2rZJ
            rsQRIxGuOJNh8j81Sduh9pzo+VnyAt64ld3jaNZnmtKM8w2R9V0OOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZExKb0lObjNvM0Fibjc4
            YkZHTHI2K1BIN0Q4RTVWYitKUGxJaStRdzN3CmRMc0s3YmxjV0lWVDVUdURxWWFP
            QXY2K0tnQkwyOU5meno2NS9zUitaVEkKLS0tIGdwL3V4UXZtMkZJcjhtbG9UOUJS
            cTdvaXp3ekpUSVY5Qk9yRXlLd01ETGMKcY14jEGPuCyPhANvpqM/Gx8evSPioZVt
            ltH746W+NPTSB2X93hhaUecI9lll/JdsGi36Js+RbS4EPbpvh6Ag5w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMHVITDE4MGZ0Q0tCOWx0
            bmphUUozMENTNzNsRDhPcEdUWTZydTVFWWhZCjg2cTl5V2hTWU1kc0ZsTm02UXV1
            WGp4dktxVTIyeUtTWkZqenFoUTc1VXcKLS0tIFlKWlBBbC9tRjFLNnVHUDNnaEJy
            OTNLOGFna2c2WlVEQUI4dUdlMjE5UmcKybg9ESbenUHO3zWWUzb8qXN1O+gAJ1UK
            WQJgabZjWrnattqDQf4midUWa2/0krzy8H1U33znzw0m0sYnqHNHcw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZTBoNCtYSUFMQ0lkd1Rs
            VVVGQlpXVENndlI1UTR0b01aZXcvWEtydVNBCmZEN29ZVG93RkM1ajVQTmRHc0Zm
            SmY0R1VaVWpYTVpvcDRSYmIxcDJxdlEKLS0tIG92bzd1L3RxQTNJb2Y1Nkt2OEFx
            NU5lRkRSVHhPbWRraWwwbmo1WVNPTUUKRNFTgDlSNtxSZUZnRDHdC5B3YYt6DBNB
            Nv3bm9AdZSllSp6QqxBk/RVgZo0P0kT7k958pZPB/KMAd0gUEWbAPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T07:33:01Z"
    mac: ENC[AES256_GCM,data:I13RnWiOV8eLDGaJbOCJKmEuJcDIc8BomSEGlAdrMH1wNf/dAFe9AbBqQnx3fJFpgE0MSl/MnXLi5gOQnxxYLS+SerSbueygd74vvO6Kx/77ZlydrNHncOenabfRA4veYjWb4ZRE0y4jGJfnTfQu/jcFpFskRWtvlIXoLRNHoHA=,iv:UThj6Bpo0pabvmA5j+R2lFAcnIXjkz6CGuvuEEs9j4s=,tag:t6bD5cb3r/Di4Zyk7MYiMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
