apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secret-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://isindir.github.io/sops-secrets-operator/
    targetRevision: 0.24.0
    chart: sops-secrets-operator
    helm:
      valuesObject:
        secretsAsFiles:
        - mountPath: /etc/sops-age-key-file
          name: sops-age-key-file
          secretName: sops-age-key-file
        extraEnv:
        - name: SOPS_AGE_KEY_FILE
          value: /etc/sops-age-key-file/age-key.txt
  destination:
    server: https://kubernetes.default.svc
    namespace: sops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
