---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: backend-stripprefix
  namespace: taqueria-bonjour
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
  namespace: taqueria-bonjour
  labels:
    app: taqueria-bonjour-backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bonjourinc.com,bonjour.bonjourinc.com,bonjour.paulynomial.com
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: "(Host(`bonjourinc.com`) || Host(`bonjour.bonjourinc.com`) || Host(`bonjour.paulynomial.com`)) && PathPrefix(`/api`)"
      middlewares:
        - name: backend-stripprefix
      services:
        - kind: Service
          name: backend
          port: http-backend
  tls:
    secretName: bonjourinc-com-tls

