apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: taqueria-bonjour-twilio
    namespace: taqueria-bonjour
spec:
    secretTemplates:
        - name: taqueria-bonjour-twilio
          stringData:
            account_sid: ENC[AES256_GCM,data:2UhRmRGzSw4inQEikgIBd4hnprf/mEdhg48zrfY+8NHA9Q==,iv:4QUx7dhZJRvG4AoL5BwUbJYajFn9+cckKacweZkEeGM=,tag:rSKw+MBqCXvFrNOEMuPyhg==,type:str]
            auth_token: ENC[AES256_GCM,data:QmSlfCVrewvHISn6V2dzYyesiHEEbjN53czBcCuUspY=,iv:SM+q4EuhPdZgJ9XPr6hiI4NZigUeCI8v/o3cLYKi9A4=,tag:ocNbl7uylx0g+9e3NzZLtQ==,type:str]
            origin_number: ENC[AES256_GCM,data:zE2qjvlzHrASg0LZE3M=,iv:7iz+/Zb8kFHt/gIgUO57ONOuklMd+tOPZEjqXQlyvVo=,tag:ntcMuAbon6mIzXeFQMyOpg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSFRpNXorSGJDYkhNZVJv
            NS9WZi9NeGpaVXQ4L3VuR2JVTGpJWXhnOEJRCjBJR2FRN2dPMVdyYnR5NHJwVXN2
            NTZTZy83YnVJL0hQQnJjalVteUxLbWcKLS0tIGIzd2drUmFPemJXWDlycnY1Q0Nw
            QVROdUNnZkN5dXZkTXNqdi9DemRDM0EKWrF90F0KcXy4lFLOTo7OoO3UaVuejN6j
            MC70mAt7sueX2ZSOAxHMRwCV7CQ3cdN28G1WT3U1YCu5/+X0lXOwUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbHZsWDdBQ0hsS0s1SVow
            dDY4bXVMakJnRHFCQkh2dkxxaUkyZ1B1Q21zCnE0amYvcDNjVlV5MFlySWFDa0hN
            aTRGWGs3MlFKZ2JpUDY3MlZxeVI5QjQKLS0tIHFTalJOc2x4aEJUb014R0s4T2Mx
            NW1hU2R1ODM5UXcvbU5vSUR3TmthMkUKnSFWhrg3Kzaiq2VDeZ190KmK6ShNyBEB
            MvM1kxuS0DE0l0Crh4aWY/5n71xGCYVDk9mBhx3ebGRt1aVD7Pn8Ag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWjV5cFpXRXlRS3A4cDNR
            TXN3ODQ5ZTM0YkFzN2NIMEI5WWtrRFBiL0NjCmRaNlVZaTNCOGpnWXJ6QnljN2l3
            SThFUkhETVFJN1UyQVpGS3owRkNDalUKLS0tIGd0bzlFRGcxaTlHWHlSZG52S2I0
            SGpadmVxOHZ4RDJGU1ZIUVNCUUM0d1EKawDTQHHarrtPqozJ3bcXD+0p7pRpfCRn
            nHnYhruGMtaNBTvY/i4cnxcVSbzJLRt6PmaxNWA638XU4UY4B4I+DQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTjdieFlTUktBVU42YlN4
            QVR2cmYrSTU2SktFb01Gellqc0tJdnVhcFdzCkJxWDR0aytkUzNOakRESmxVbFBF
            OU1IN21ac1E0WGU2bXBOSHhHNkw4RnMKLS0tIElrS2RxOEh1L01wajV2a0VIRXRz
            R0c1VllYRHZ2eGE5cjZIRjVNNmhYVHMK5yZPsMnXDrLNRTW4Pyg1VqYmyL1djoDy
            xrYUdBwi2m+CmhCJaJtlidZ+z0pxOmVVHEU2Z4DuhzyrRCNT8KIGCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQVgyQ0pSL1ppSFhueCtK
            dEhpbHV0V2REbVZSREFvZHI2a2ZVVnIwdDNnCjJWY0V3anhUWjZkUytseHNiU094
            dGtiakpFOG9zUzR2TE5Ha0M5NUREOEEKLS0tIHlrQ0k5VDcwSDMwVTNJVWRMZnRr
            SXVrRndiTUFsRUMraVYvdzVlVzBXSVEKTtgh7cicfE9vtLIChSkoKOJKG0x6B7cB
            s3rJHm8s5uCj3cp3lBu2el0o9cZOm42++/iBA/3Gdp5f1YpP0zrB1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWFJ6NTZPUHBvS3phZjVu
            ZTV4Q3ViUGFlMk14T3VaSC9IUFdhaGRQWUdjCjNVcXQ0ejNTTWdhN1FKc2Vmbzg5
            VjJlb1hvaWV1UiswN3NYY0FzTGhob28KLS0tIFFpanErVHNhOU90ZnF6NHNxMzdT
            Vm42dFRmQ2c1QlpaaTNNc1kxZ1NZdTQKoySMR7XEggzc9ipRtVnumyIG9G4YtbhZ
            3c2G023FCI/Bwohg0ViTuROoLnI4Q+dznwOz9dsFVfqkSP7Xn6aZMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaW85UjlLS3c0VXNlN01I
            N2JXNzc4ZUNUTFZVMHE5MWJRV2U2OGhkSVFvCnU4OU5LTDdxWGM2K1M2STIvdTdP
            OGI5WkxUcUpCZnAzL0N6RkFzSjRmUUkKLS0tIGNmREFBRktPalFUOW1QV1k0cUI5
            a2h1RHE4Q3ovYWo1Y0xQWVJHV2Q2ZUEKmpsX0NFXszt8/me4Dx6Q1m7Q6enRc5Cz
            Z949WeqBHn0i2eG1VXk1SCDioJKtddemSrtr9mbjGsfuuCgzwPq5uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:16:26Z"
    mac: ENC[AES256_GCM,data:ok81S0AqP7BHZCo7PlUnT4B1XEugwKp9N3fiTAldBUn7U+syqXx7CAaUqB/MWqWBaal1v5SnMh27WUmKI2ybd/yJVSc22onCzHKgAufnfz2vA+HOd2MwaHOXzMKS+60y3wSGrNwtlmUTbmgkP+9bMuMEkL5lqkanGUS15xGcSm4=,iv:gNDqpmrUsUG7936h9cIcZieloDmC3S+wOpvuTwVgzB0=,tag:fJJSieAPNwTg4Q/U450L/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
