apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: taqueria-bonjour-twilio
    namespace: taqueria-bonjour
spec:
    secretTemplates:
        - name: taqueria-bonjour-twilio
          stringData:
            account_sid: ENC[AES256_GCM,data:2UhRmRGzSw4inQEikgIBd4hnprf/mEdhg48zrfY+8NHA9Q==,iv:4QUx7dhZJRvG4AoL5BwUbJYajFn9+cckKacweZkEeGM=,tag:rSKw+MBqCXvFrNOEMuPyhg==,type:str]
            auth_token: ENC[AES256_GCM,data:QmSlfCVrewvHISn6V2dzYyesiHEEbjN53czBcCuUspY=,iv:SM+q4EuhPdZgJ9XPr6hiI4NZigUeCI8v/o3cLYKi9A4=,tag:ocNbl7uylx0g+9e3NzZLtQ==,type:str]
            origin_number: ENC[AES256_GCM,data:zE2qjvlzHrASg0LZE3M=,iv:7iz+/Zb8kFHt/gIgUO57ONOuklMd+tOPZEjqXQlyvVo=,tag:ntcMuAbon6mIzXeFQMyOpg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUCtlYW9NR0FyMFNzYnRL
            OTRad2dCV0taeGw1V1JtcEcyMk5QT21CenpjCnNaeGlhQ0swYUZCcEJveG5OaHlk
            Z0UxQXlVd1ZOUENNYUUzTG5HRThMeDgKLS0tIHJ4UGRETXpBVENhR2xmUi85MTl1
            UXhpR2VNSHhWN2dLWWM3SC9qZ2dVM28Ki8FB1EvdRB3mLNRdrLyUHcO6RKYkrOOt
            9aKgRsrvEqE7X2WgQLMyN5oC86yrb+xuALQowLO0n88+vVUu3zX2IQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZnQzUi8zaXB5SXpucEtN
            MXY1ZXNsTnFKUnBveUNNVVhXYk9HeExJTldFClJwTklHUkJGMVF0TThRcFV2SjYz
            R1JGNDhxcUVwYVVUd3lKYUlrQUNhZjQKLS0tIC9oUFVFOFd6Y2pqNGNGR0MyT0M0
            Rm5Nb0k4d2R4VnpUdElEV1dScWlRc2MKF8dBPxF5T6c+fQnTmhkB97xbBuWzOBL/
            xt63/0NNwLkXYfRDK6S0PJGPsUvg4fZJQq4LgojnlabBmxECe2sZ8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UlhNSHBKYnA5MzhxVndK
            ZG9ESm1YMHlWd3VHTUVZMFRSaHR0Rk4rR3dnCkxaVlV6MTFGSjJBTmx3TVVaeHFW
            eEFPTWxCYUlvSzFMR3RBcjNGVFl3YjAKLS0tIGdUVjdNbEl4d3gvYWFGVkFUM011
            TUlleHhCOFljN1hHdGRuVFlEOERpamcKWG8Vy9c4h/ULwt5GAnbygsyMH2tbQvJJ
            JVyQkKIWRvU55jnir7pSRGk8s/7WavBbXCmT88LnSnmLJ9T1i32F1w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOFNtM1pYQW9qbzRKbGQ1
            MDVrbmtTMWJHTGgrQmZ3K1dleWN0aTdOeFRVCkJGYlk5QWtSTkhKNVYwenB3ZFdo
            QmRKcUNqSEhsN0RHZE9OdFlmL0JpNmcKLS0tIDRmbk1EcEVscWl1Q0dac0g4MHoz
            WWREUzIyeE5XbDFEK1lOdmRTdzg1UmsK5TARM4K/4SF4LVA2Gx83C/MZOZGr49N3
            ifrVdP7jYjMub5hZinKaiVrHBKo2hXfoDO+7WbGM//0OeNJcAHvdbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdHp0b0J6amY4aXFKODF5
            SU16QVJtYTNrY0s5NlZBRmRWNWNhdWtyZmxjCkxXNGJyM0lFZktsTmxtZkJiUk5Y
            K1VlVVVYZ0xpZUtJM3NrWTVqay9PblUKLS0tIHBjckV6eEpuWVZlUDVGbEhPZjZr
            REF1RlR2b1hpQWZJL1gyUWh2Y0xnRHMKhyrCL0cH3GCUgmcpeDFuEloGUm3N8A4A
            28gdRtqMdtTKE7kUS+vbqZqLYs0sys4wPjP+Lm7EIYulg8/Ke13VvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKc1BYWHdaZ3pHaWZLZ1V0
            K0dzTGlpazZGVVF2dFd5ekwwUWwrZHV1Y1Z3ClZndkpMdU1pVlZ3cCs0akVxVFJH
            Z25iL0NYVFJqa1V6STliMVQvOTRVQ1kKLS0tIDhoMUpzWllScGdEb0VkSnhldHA2
            THZjamxLOFBuYVFoSXRkL2RwMjlLUDgKhob4udnaHMrz30QjCtt9IwG8bKI9w7np
            M3aUcVdCMrOl6UnjmAp22JjKXT0VBNw++32Sx6aP2cbqyvocWsz3xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T07:16:26Z"
    mac: ENC[AES256_GCM,data:ok81S0AqP7BHZCo7PlUnT4B1XEugwKp9N3fiTAldBUn7U+syqXx7CAaUqB/MWqWBaal1v5SnMh27WUmKI2ybd/yJVSc22onCzHKgAufnfz2vA+HOd2MwaHOXzMKS+60y3wSGrNwtlmUTbmgkP+9bMuMEkL5lqkanGUS15xGcSm4=,iv:gNDqpmrUsUG7936h9cIcZieloDmC3S+wOpvuTwVgzB0=,tag:fJJSieAPNwTg4Q/U450L/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
