---
kind: Service
apiVersion: v1
metadata:
  name: gibson-webgl-service
  namespace: gibson
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "gibson"
    tailscale.com/tags: "tag:k8s"
spec:
  type: ClusterIP
  selector:
    app: gibson-webgl
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
