---
apiVersion: v1
kind: Service
metadata:
  name: gibson-webgl
  namespace: gibson
spec:
  selector:
    app: gibson-webgl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gibson-tailscale
  namespace: gibson
  annotations:
    tailscale.com/hostname: "gibson"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: gibson-webgl
      port:
        number: 8080
  tls:
    - hosts:
        - gibson
