---
kind: Service
apiVersion: v1
metadata:
  name: gibson-webgl-service
  namespace: gibson
  annotations:
    tailscale.com/hostname: "gibson"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: gibson-webgl
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8080
