---
apiVersion: v1
kind: Service
metadata:
  name: adguard-tailscale
  namespace: adguard
  annotations:
    tailscale.com/hostname: "adguard"
    hajimari.io/enable: "true"
    hajimari.io/appName: "AdGuard Home"
    hajimari.io/icon: "mdi:shield-check"
    hajimari.io/group: "Infrastructure"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
  ports:
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP
