---
apiVersion: v1
kind: Service
metadata:
  name: adguard-tailscale
  namespace: adguard
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "adguard"
    tailscale.com/tags: "tag:k8s"
    hajimari.io/enable: "true"
    hajimari.io/appName: "AdGuard Home"
    hajimari.io/icon: "mdi:shield-check"
    hajimari.io/group: "Infrastructure"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
