---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-tailscale
  namespace: adguard
  annotations:
    tailscale.com/hostname: "adguard"
    hajimari.io/enable: "true"
    hajimari.io/appName: "AdGuard Home"
    hajimari.io/icon: "mdi:shield-check"
    hajimari.io/group: "Infrastructure"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: adguard-adguard-home-http
      port:
        number: 80
  tls:
    - hosts:
        - adguard
