apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: cloudflare-api-token
spec:
  secretTemplates:
    - name: cloudflare-api-token
      stringData:
        apiToken: YOUR_CLOUDFLARE_API_TOKEN_HERE
