apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ""
    credentials.json: ENC[AES256_GCM,data:1aqVOZjAw0ODZbUZpD77aCn4xVKNFfzmG31AH/fs2Yv+Rh+90+NP2Qx3GyAv/5R7Y4I9YJtZTsraKm10DKVF,iv:uEzcnCc4Xu3Am3s+qAxIA7YtsXxerTaeXloKEZrokgo=,tag:eoIALAAV+DFZBcKrY8FW0w==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV05ndXAwTVdHZzVNbUk5
            OTFoTWhlZFd2ZFQwNGZBcEszME5leTdJMTM4CnNDNGY5MjZZMzAwd3FMZVpLckJq
            Mm5sQlg3NDUrVjJHM1FLSHc5bzZMQW8KLS0tIEhLWEg0bHF1OHpDWjVpcW56Mmoz
            U211Zjl2MHF3VkZpSXE3RDh6azdJVzAKePjvcru2oYB1kDXr5kpQy4+vqf3koyWO
            aGn9PVyJU13VAuRiOOpwBHP42e9vtp/atnR3t+HoBEHzK1mEytTaFg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ1VmdU4wUHd3dkhDalp4
            VW5kQlVJVWJMMjV6Y3BvYkc1Y2tiRUNBQkhJCjIzMFl6L2dvaDF4eUdhMmtDVi9k
            VDRuWFJaRWF0ZHd4eWgrTGRzVUtlTFUKLS0tIFExVWVwSjFTWXArQUpva1dxaWxN
            OURFS0k1YWFCWGdlSlJOeFNZNkRKTmMKzNjjk1Ou0UGxKWIjZiIZSLxwroYadid9
            6T/sUYLzmhDxbSb61RWKjDZHvgcvH820c556XbcVIeHwxxSAGjxTaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdWZlWHFhaTVDU2N0Mlow
            UERHOXRSNGpCSzVxeGhwaFVnekYzcDVpdUVNCkZBS1VtcnU0RzVyZGluOUN1ZTNL
            c0k5ODdyS3g5K1lWWE5JdTJqK2V1N0kKLS0tIE45T2s1NUZLa2RkWE42L1JHZHdT
            TUd2QlgrRk93WGQyRDR0d0ZXaDR6VDgKMiSco4+xa6bGqVrfMzpOc2McT0E5Dq4K
            xIqlYoQk7KQ5/k3pZjO40PrgeILZULtTiU3xCBuFZvUf5xSk/oEZQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArc29iUG9ZN3dQSURqNG5t
            MXAwdXZmb2lkbDlGUTIxeU1FbmQ0UFIwTGxFClpGN2dXT2g1M1RuM0p0L3FLQzIr
            ZmlGU0lidGlDM015QUZNbEcvYjd3MnMKLS0tIDRQcFRseDNRM0lYQVlZa3hwc2RE
            OGpwQUZYM3FlODlOWEFSdTlSSVk5RnMKnsCZ2MTxnbixVZ91sXzmENqM1Fim3TF/
            I2YAEGZu2b1tFAlc8M00eneQhjDvUT2MWmA3hvqo9wdfBWi532vlwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVHpGVjlOOUx1bDQ0cWpy
            MVZUY2xNbUxvL3laWGt5eHAvR29TZzlyK0hzCnVHamZ2UzdmeC9wTWtPVmd6dHh3
            d1JLNkZYNHN1bHZxNzdhVFNyWkxJTUkKLS0tIFV3dzFnTlRSakhqcXpiVTZJWWFy
            dmNlV0FRcThXWEJwNDRjOXZJSkhyVFUK+3JrYLhJ8d502zRDa6G/hBmp14Kjimlo
            yrVJfTq64y7d/0i3snNPlaQAkgLJoz6SCTvqaxOWK0EBmWpcxa8u0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T07:06:26Z"
    mac: ENC[AES256_GCM,data:aaBJyUUtLx9S1IuiVSWl668/DHtTr2WhtDColgENUKIMjenazu77951tiBZeVJRD5iWuFdAfksW+7pgo/Yx0uYieYIatm+y6SEV3wuKRcufCEAjX+D0qeEG9edugGvA30wldAZ8uXZM3DNiRujfFQ6+w1pQv7hLe+yvUbaTMBdM=,iv:S+OuZTSTYRqJ2necKfU7WMPYRMsuYXlArtZ0XgoddT8=,tag:XxQP/GwDD+n8gbDz+tTu3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
