apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-tailscale
  namespace: monitoring
  annotations:
    tailscale.com/hostname: "uptime"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/name: uptime-kuma
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
