apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: disconnect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/paulkiernan/homelab
    targetRevision: HEAD
    path: kubernetes/argocd/apps/workloads/disconnect/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: disconnect
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
