---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chrisabel
  labels:
    kubernetes.io/ingress.class: traefik
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/appName: "Chrisabel"
    hajimari.io/icon: "mdi:heart"
    hajimari.io/group: "Personal"
spec:
  rules:
    - host: "chrisabel.love"
      http:
        paths:
          - backend:
              service:
                name: chrisabel
                port:
                  name: http
            path: /
            pathType: Prefix
