apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-db-user
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:kSKnFdIw,iv:pI5TL2KY2XSfgZkfhZjmmJvQ0kZjLmufg+ukxfZn8x8=,tag:Pe5D64I7rDecS5WJTcpXFQ==,type:str]
            password: ENC[AES256_GCM,data:+zmMeXf/IEn/d3XMn1Ro3dYInja6E5WBfuYAW6aeIQ==,iv:mE/VeyFizZB3hhLBBHnb3dJ0fco3SVbxCza/N9Jh9PM=,tag:qo4RT/eZ4+BZGL/P0SSikA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOGVDQzVxbnJva0ZRY1o4
            cm1PZE9BNUJrMGtWUDBvcWVUL0tFVW4xV3pnCkRyb3FQdDhha0FjTmw4MjA3bytV
            eHduMmRHSXFHdzNpNitmYkcyL0gyMEUKLS0tIEkzSjVHcmVBanFuakpnN0VUN3Bl
            SEVFVVgyNVc5eW1zVld1aFQxajJIMTQKTUEdDzz3Bx8l2xr8Z+FkIJaQAUHndKMr
            tHHfWQ9ctSbjfwxfw5dHeDSHKUajCqlXT72HcYq/+0UQ//Io3CJ/fQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcnNxd0RHTHVKS2dGb2Nn
            YTVoSEJkM0hwV1VYdjB3QS9SYklFeEthNFNBCnJJZXAwNW11SnByMjRGYWRNRkJJ
            bnh5TXpPbEJvZ1o1VnhCblhxOXJGa0kKLS0tIGpvYlFXK1g4aWF0bFY4M2I3RGhi
            a2xSaUZJc254RXJhTytBYTRzaldrYW8KP6Flvw6cWXzm6JCGtE8yBsA1OQM/BlM2
            YttuNpnLeORi3U0TNUbqjkL/3F3GtzL4/7rT1Oph7sxIHjznTrobag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYb25LNUxSdkVBY3YzU0gy
            eDhQZXRmL3lLYTE0NkJ4Zm8wK1NvTmoxWkZvCm50YVNOUHYzWjZPeVJtY0wrNlNX
            dzRlZWJDV0ZlUFNLZjhQQUlvMEtXd28KLS0tIHh1YjI5WmtiWFFWYzNSM0wxMzND
            NUhmV1VJNWlrRkczK2pDdmpsTldNbE0KTdu3n02LbnDIHFxkAaLN1rcmmo3NO1jM
            ArXre+Mv35Pu8/7SCSxfEuRBLYEr18v1x2795Ysbf4jCkKE1tEE5cQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQWZ1N2trZ0dZQ2ZuNjZV
            aUhXbnV2b2N6RHQ2dTcraUpWbldSV21lUTBBCmhNdjJiN2NWbWdPOWcvcU4rbWdE
            bkdZSEFxa3kyMjBCblFFaStOdEt4M3MKLS0tIDg1eTR2dXdvSEY0TGpGOWkrM0s3
            Q0dhZXE4UHhaOXBFaldlc3VkWjZJb0kK+LxyP1ftzMetvN/YfxkzKaNRJly8694R
            BOKIEBMyJQz7n/znTPEFllSKqnIfWtj0QUZcz0YnURZURkH/8UkXMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnT2tVbTZ3V0p5SFM3L3pJ
            Nkhka3o2SDkzdmhRUHpwdzVzbnpIWkswS0g0CjJZRGwrQkNubFV5N05VL3FRaUV1
            WGVGVi81UGVGSEtBd05HbzhDQ2VOcUUKLS0tIGMvQWlsaTYxU1JVVTJxdWtKYlIz
            V3c2dzhhSWtDS1VzSExWSjJVK21TckkK85JysbhwrQiG2zD6dgAbOIHJfbL9t4Md
            SR6bVKGNF1irjDT+kSMxxfittQ2FrOc0JywaDsHY7/Wb6RNJSigvHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dW5DN2lJZS8zRlptL3dO
            b25rd2pzSnA0c0YwNFJQa2RUSVV2dUhuQ0F3Ci9CR1hlRVhFcldUaDQ0c0ZvYk5j
            Yzk2WG1ETDdndS9nYWFteDRKSTE1TXMKLS0tIGhaVjNOSDZkMWx4K2o2TGxNWFhC
            aWQvWGRTd2xvcTVsR1Irc3BPL2YrNUEKmFdSviqU1Vv8DWofkZStIyxc8u9VfaE6
            ASseE/rWJZVZloSjtxxTYwjNZ+DOj8+F/OAKtt1AGOZG1vXD2AVAEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzlRMXBQQkI1WWx0dDl3
            NUxwVDJiYVJwK3RSMDJGVDFqdnQ2ZUZhdkRZClB4UHZzVWcyY09rWEtNTHQzYzd2
            SUpMRDBuTEl4b280bWZQMTBibjA0djgKLS0tIHNjMmpyQ0dmeTV0UkF4UGM4bTEy
            VC9CV04vS2lyYy9Nd1FOUWgxMTl5VVUK7eRxXN2PtmTgcImrlXCbBa47FkmvnLdy
            80QZQyfN5xe/b/IbviVCvV/x3X4wesymEAW40HLDY8YyrrtaEXfvyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T22:04:51Z"
    mac: ENC[AES256_GCM,data:DlxLz2L8j9WBRSY16ZyrjxQyNPkwhdajdgoN/tcb08SIbSU+MnYXM5BAgCmQFb7HLR7wlrscH3cvVDJE0YM4GHCo4CCqahSX22N5kQhosGd+Iu5jxQrJ7mVOMsBSJNSp07oNeCqx9uXR27SBU9w26g1ErZ3ZJBGT7ejJ8+x4aqQ=,iv:SnTmzSofy6htgm8AQqqXiW6WNh/xV+myBcAJRJ3F/L0=,tag:qJuq+z+mxTvXI1Th9T698g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
