apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-db-user
    namespace: immich
spec:
    secretTemplates:
        - name: immich-db-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:kSKnFdIw,iv:pI5TL2KY2XSfgZkfhZjmmJvQ0kZjLmufg+ukxfZn8x8=,tag:Pe5D64I7rDecS5WJTcpXFQ==,type:str]
            password: ENC[AES256_GCM,data:+zmMeXf/IEn/d3XMn1Ro3dYInja6E5WBfuYAW6aeIQ==,iv:mE/VeyFizZB3hhLBBHnb3dJ0fco3SVbxCza/N9Jh9PM=,tag:qo4RT/eZ4+BZGL/P0SSikA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd2x5RzYvZVduN2xpS05J
            dlhxZ1BXa2xPWE1RUEhVdnVsQ3pNSE4xSVdVCmloK2s5L1g2Ym90R2wwZjhNcldZ
            SkhGWDkwQmVDVmFHN1dNU3JoVmx3TTQKLS0tIHdkaWdrcEIrR0hnTlcxcmprUFhZ
            WmZWM3M3My9jZmc5L3hDU2Y0Y1ROdDgKl/Fscx932r0Rh4WRGCIEMrPPqgWCpdRi
            CeX3UNysBjxjoAb1xuACgKMdybzaHNGYyDLuTiVvcqKO0aPxtOr0Xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZXI5dklHcmV0cDloVmZR
            ZmRIazg2c2hOUGdUZEFNcmhCeng2Ym80bGhzCm55VitlZUN1cjZzV28rTmhMT05C
            Vm9iUlR5SDN1dDAvcm1QTE1NNlJ3QnMKLS0tIHEwUnJRM0tObUU1eDc3c0NBS3E0
            SHlYSThhK0tYdkxvR3JVYVoxNVBEYlUKvl7PNccHSQ7ZlIeGl77UBT4HuKapUK95
            JwIsveuyUsWvftui7zFNKp9t3UVX+cAEb6Girlj6QeXG4R7NFS24HQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnM3lvVXJsbFQ4dS9LNHVE
            dnF6UGRFRURqZWdOU2R4VUJGaUl2b2ZndFcwClpTZVFnZGYxUDJNZTQ1S3VBYWFB
            aFZGd0s2bEZyOEtWcmpsRjhRTVNnRVkKLS0tIE91R2FMK09uSnpPa0JydHJXd2NS
            MkJGb3RxaDNPMUtDQW1vMXdmc0J5UE0K25pfEi6LtO2PMPvlSwDLIntb1bIxvBD6
            yONAbG/vV7ZgEh530m8Dzv2TBVQVC1MtI9DzG6FL56pyz2ptIhY8Qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa0czcGtOb3lvRGgwcVhD
            V2NaOHlBaVg5MnFOVEFheWlDSGVESDdnMFRJCmt0T2FQYWFuSXhRTWh5NUtCMjhD
            VmNqTVdXUEI0a2xSVVJRaC96QThMUVUKLS0tIFVWdXNJdjJ6UitVT1R2MTRUZG4y
            OUNCSWt3dkVldlpuZmRLVEZCeEs4WWsKTsZJeEVz1oWiU6bbkpRnHCnCCrBJCRWB
            /kaq6HJMA8EKpblaWtytcZozWFQyuSKnb9SCcFh+N7LLzPTu+inQkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVTJGaXdwb1JRK1ZobzNP
            R2JoNWUxWXF1UU9iamVscSsyQmhGR3lOYmtzCjllOUxyd0hRZXB2THpHeU85NS9z
            Vnc0UWpWekgvK2xUb2FDRXg3dHdGZ0EKLS0tIGZkMU9yT3czTk1WZ0ZqczBjOWM4
            elVadTZHbEpzWUVETmcra0I5THArbzQKanVnNonOU2qs1NSCNejolda77tlaqz+Z
            BbvJmukNXmvJf4tElGK22AwbGanfClTLpVH6sg/DpjP4K+jxPfJRBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bno1SUcxY3R1QWIyV1FQ
            R05qWlY2WkRvZkp1bU8raG9vQnlBNEhhNmtrCjBwMlpDR1RscUQvN3RXS2Y5VTJq
            ankrdXd3bzhuUERLQTRNOHlveVFCZGsKLS0tIHpPc28yZ2w0MkMvam5qUkRQSjIz
            S2orbE9URXlqVjhDVmkxK0xCRW1aZ28KUvzGpBgVrhvlyd//Cfhm10oIL3NEdAfC
            cyB/8mJIx2+xFosswP5958/z0K4HoSFJEWS8D1lMd/mJ9Yop47Wudw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T22:04:51Z"
    mac: ENC[AES256_GCM,data:DlxLz2L8j9WBRSY16ZyrjxQyNPkwhdajdgoN/tcb08SIbSU+MnYXM5BAgCmQFb7HLR7wlrscH3cvVDJE0YM4GHCo4CCqahSX22N5kQhosGd+Iu5jxQrJ7mVOMsBSJNSp07oNeCqx9uXR27SBU9w26g1ErZ3ZJBGT7ejJ8+x4aqQ=,iv:SnTmzSofy6htgm8AQqqXiW6WNh/xV+myBcAJRJ3F/L0=,tag:qJuq+z+mxTvXI1Th9T698g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
