apiVersion: v1
kind: Service
metadata:
  name: immich-tailscale
  namespace: immich
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "immich"
    tailscale.com/tags: "tag:k8s"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/controller: main
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
  ports:
    - name: http
      port: 2283
      targetPort: http
      protocol: TCP
