apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMUczZnJTa3VUdks0WUJq
            MDlmNDhQTHNIRHpic29iRVE3ZjFLUENHcVFjClJKUnREMFBkVjY5N1NSV3ExZUU0
            bFFJT0UxMnlHYTEzU21JOTNSSHdhb0EKLS0tIHRXK29sM0dsdkhvOEVhdUZmd3dV
            Qk5MWjVESi9Sczgwa3Q2SXBUWHFFZmMK2vV21EV93x/i2AUUBq4/DItWBoOhGKjW
            MNvNo3VFNjsmFZ6WmyB5N2ipQ+sm7ew6C/wVugohHKcSTY3GQbaPCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVjNzWDZZK0RiY1pZVTlr
            Y3lJT0FMMlF1SWdhaEFCK29MZDIzVkt0N1RZCnBuRVY4OHdGVXhPbDVNOEk3VSth
            NkF4aGpINkpNWjdZbGgrZ0NIVXJIOTAKLS0tIDRJZDNYNXg2a0h6WDBMUlA3TW9v
            TE82Q1pjUmhEd2lQT0wrbW5ENXA0Y0kKHsymchPv4ngPAwmMha4o8IPmchE0tDS9
            lrnkQaBEgEcU/VTdEYnibJa34+izuPWPXdA1PiGbF4Qx3/pxBn7h8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYll6bjZPbk05eG9Md3Ny
            RWpHL1VJbEFXVTVDRzlmUGJZeW5EQm12bkhFCnN0TGxsQXByZExac2lsVmVHNDh6
            S09CM1NYTEIvN2NOS3dsZjZNTGFTdUkKLS0tIGNydnc0ZW5HbFVRNSsxQlFBVVZP
            Vlc1cGl1QURNaXA5ZjlmV2NKSHdFOWMK44goHx6bOF0z1paVbP0qvbiV6C9YKLAc
            pfbEfCeJiVvZzW6137O5RSPbHus0jbpN1auje1SVL/AyUrhj6MX6lg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ2JxZXp4SGt1NHVYNDJ3
            S0RkOGkrYUw3NDRQeUQ4bWozc29lUEgvTmxzCnNYSTJtL1RCa3F3bkg4ZVN0L3h3
            M1hIN2k4UVJKdzJieGhtcDk5cHZvb3cKLS0tIEdRd284MEJ6N3ZMMmJpVHliQy8r
            YmFhV2FaV1RRYTRQMHk1TGljbW9FM0kKvQYH7mRbnqKEFYDzSgPwLppFaSTCz7Xw
            hD2wQTWdq8M8msAdJSicn4I8zAMlIDwBhtfbStHL2QA+aO0CYP/htw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvY3drWU9GR3pUcTFUczMx
            Q3poaXQweVJKaHpiYWtKT3NtenVXWFdFcDJVCjE3Y1c1aFFuMk5FRTNqZWYzVW1a
            R0lCWnhUTjM4K1ZGWGlldit5QmpSZDQKLS0tIHdOalozbU8xemlqaVZCTjE3NlZh
            WGpWZUZzSGJReHpWaC9YZEJoaE50Y28KZvaHb7Tcg7TN1EeWOZDuVB4n/KG5f3pC
            h/eHRKRwvNn79GSLH2WtuL0tohaJuEm8aYPcXNw/bggNe75xxTmtLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T07:06:26Z"
    mac: ENC[AES256_GCM,data:GhvDpA88kBy6QJDwJugngGC2vqNKMhicdBTsViJbjXWJY6/M2EiIeQLJriLruM8n48ZCcEi1Xy0qONL82ZvQqHVx5YUjh3WRnh16t7yEuBTXAs85lNs/2X8SNQaVIj1tdzwqU32b/h3fXGcIQDSxon+CZzwVhgb+1bChISr72CA=,iv:q47dB4XiNwX5hQ/O5c1ilJ/Rhhe4egEar8nzrZPSBh0=,tag:JiQAfuUK35u5zpvMW6J84w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
