apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ""
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVU5jL1NoeVJBSXdCTkVD
            NlRXTjEvRy9vR2NKZlhUYlRWR0IxRXNsUkhVCmt5bm5ndEM1MUZsM2R2RStRSVhL
            RFRCNHdqdlhaV3dYbDJ1T0JOalJ4TnMKLS0tIGJldTl4WnBhcjZWQ29zMnJ4SFA2
            Vmp1aC9raWphT3NTQ1FvWitReSszZlUK+HfAgwDW8cLavQJ+LLAqDP4bbEA5OuTF
            CsOth1cDo76CbAgTV1W4qQLMxSRW7i50jteGocyEbTPXNB/vMYsaQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbU9WNjlvRFN6SjBXS2pM
            L1lQNTJkbUwrMStnSFhFY05WRkpwZWRGSWtFCkNDdlltMmN1Ri9pVjBDUy9RWThn
            aE5XL1BPd1R4TlMvcXZaV1JWc0hKSTgKLS0tIDVqMnNWdlNhUFZrUUFaOWN0TVFQ
            blI0Q3Jwdjc3N3lueC8yU2JrYXgvK1EKh3FJ7tKi5SwT5tNFIvkcYWcQrMwCN8eI
            zX/fGB8k82Mw67w8KiDVMiZVZsE6OiyK5h9TkLBpFq4lewuSfYB+ug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2alhzOHVHUHRQU0tJWVg1
            dU4rUVdrdHdIOFowVTNXczJNZU92MWVQVldNCmZKMS95Nm93TlorUFZvYmlBYVBu
            ZnlNb0dPVzhKeC9aaXlRcVhjNll3K2MKLS0tIDdNRnFWa0tXdmUxUDZLc3R3NHda
            NkVvbGtaZzkwQWxjU3U1SmQ4cWVsZ28KHJZRIlKUuI+X8QhR7P2Tq49OrrJIm6tv
            MsgPVHE5fjTe9oNxaHdoCuwkgTQjgE2oqzAdlh3/5vHLlkHrNPHUiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaR2xmRzF1a1pnZThxeVJv
            RThmRkZjeDcwbmtuSjFicnNwM2xEYVFuN0VvClkwTVRtYmpzNGNEVzBsSFlaV3h6
            WlYvekJxL0kyZ0YrcG9ZRXFqR2ZlbGsKLS0tIExlaEluMURFVmFJdFBsdkFNT1Mv
            eU9IYW9FNzZKSHZiN0kvaHpaRWJXQzQKDycFEMiBs/3eqCO3/rvlPxHGx/kOU3nf
            XKaMqRKgW+yYuLrqoK9LdjRb5B7eEpKsgmWAXQjHAwtUHBNrAbp9rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvd05pdWVhMUJnTzlxUzRQ
            R1ZacjNaK3VydjJHQUtHTzR5R0ZHUjREd0hzClhPUjhqbDBmWmxYQXlTb3pSc1Fo
            djk5aHJpZ0FrS3hldlVxYXNPYUJ2V00KLS0tIFhGa3RkS2IyU0M5NkJmMVNNcGxK
            ZitWZGdVNkNOMjgwNWhHcGdPWG53WkkKfEGJiXfuH4Lu9IMOuEGTXd2T2Z3IyyrN
            pNCedVlE2iaGLTRaUZJDMgLrNq8ohE5DVnib8XKBFWZ6SNoroCXqNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VlVJb3FBMDdqdndwaTc1
            ZGhYWlliMGhISmJsY0VrVFVvaWVpUC9wRlQ0ClI2bHhxUGJTbE5TT0xsazBvaWY3
            Nkp0a1FSbWhxcThiSUR3ajVkZ3F2VXMKLS0tIGdMTHoybW5PeitQcmV0S2ZmNm1U
            LzNpbWp0enR5bnpzOUZrd3lvcGJLbDgK6BVjBye6+wxWldzsi6avliyRLGLHKmek
            w581rpiqbYv3RFho2pGAouliWyO5Gz9DF9kijGdHeB61hi2MQfGm2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T07:06:26Z"
    mac: ENC[AES256_GCM,data:GhvDpA88kBy6QJDwJugngGC2vqNKMhicdBTsViJbjXWJY6/M2EiIeQLJriLruM8n48ZCcEi1Xy0qONL82ZvQqHVx5YUjh3WRnh16t7yEuBTXAs85lNs/2X8SNQaVIj1tdzwqU32b/h3fXGcIQDSxon+CZzwVhgb+1bChISr72CA=,iv:q47dB4XiNwX5hQ/O5c1ilJ/Rhhe4egEar8nzrZPSBh0=,tag:JiQAfuUK35u5zpvMW6J84w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
