---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://helm-charts.rm3l.org
      targetRevision: 0.19.0
      chart: adguard-home
      helm:
        valuesObject:
          replicaCount: 2
          extraServices:
            - name: "dns-extra"
              annotations: {}
              spec:
                type: LoadBalancer
                loadBalancerIP: 192.168.1.3
                externalTrafficPolicy: Local
                internalTrafficPolicy: Cluster
                ports:
                  - name: dns-tcp
                    port: 53
                    protocol: TCP
                    targetPort: dns-tcp
                  - name: dns-udp
                    port: 53
                    protocol: UDP
                    targetPort: dns-udp
    - repoURL: https://github.com/paulkiernan/homelab
      targetRevision: main
      path: kubernetes/argocd/apps/infrastructure/adguard/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
