apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - path: kubernetes/argocd/apps/infrastructure/metallb/manifests
      repoURL: https://github.com/paulkiernan/homelab
      targetRevision: HEAD
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.14.9
      chart: metallb
      helm:
        valuesObject:
          crds:
            enabled: true
          prometheus:
            namespace: monitoring
            serviceAccount: kube-prometheus-stack-prometheus
            podMonitor:
              enabled: true
            prometheusRule:
              enabled: true
          controller:
            tolerations:
              - key: "arm"
                operator: "Exists"
          speaker:
            enabled: true
            logLevel: info
            frr:
              enabled: false
            tolerations:
              - key: "arm"
                operator: "Exists"
              - key: "armhf"
                operator: "Exists"
              - key: "node-role.kubernetes.io/master"
                operator: "Exists"
            image:
              pullPolicy: IfNotPresent
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
