apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-cloud
spec:
    secretTemplates:
        - name: grafana-cloud
          stringData:
            access-token: ENC[AES256_GCM,data:cglownX43Un38SutEwMl9772TFStTWh9CSQxEKOHhw7rvLTg9GIEYNf4+jDGiq1jz4iFE+4k24cYwYEFr8d7zJKpWFLTao1KyWOIDoBGZD5bDEw069ZaT/gDH+XbJUZj4VM0QasAtNYPttQKyEvZ6CKy9sf2L5gejI8yXrk8DeDgllLP4IaRkwDDAOwcL4cngQ3g4STI+noe2SYmB3nIffiPXIyISHykbVhtjLoX/WNHww195R1CJitrbRuT0fdrZHv6I/+59HLb/ypVkH8EX1eesCcb56p2,iv:jm+zWGPf9GIIwN9CO7X18puDdZwhiPdmxHxIN5mXEkM=,tag:aNMpa0w5H4Ft/FfrTPkpuQ==,type:str]
            fleet-mgmt-username: ENC[AES256_GCM,data:bQ6OuXleVQ==,iv:k+cG40imTQrqUyIAJ7Lb2QA0/i3IMKDVen4wwSga2xM=,tag:hYRxrZjBe23Pcl0fj7IrgQ==,type:str]
            loki-username: ENC[AES256_GCM,data:P1AhIpwG1g==,iv:snx4d/71s29UU5FpAfvS3Y+nalWW5vAJYqVtWd9DRd4=,tag:JZEbS3BO1Gyuktgy4vMpeA==,type:str]
            otlp-username: ENC[AES256_GCM,data:KrxSDMJYpg==,iv:+uwNaUg6KFEYgU6ZQTYcpvYYDFZaPH+5Mi6tvDY+6uM=,tag:HWBS15wjczjZtM41s7Ybew==,type:str]
            prom-username: ENC[AES256_GCM,data:F1GykxmXrQ==,iv:UOhdbtbO8Ye54HOLQMlnT7JrXnUvUjxAdmgW6D1bTjY=,tag:nyRHxzC1P9EeX1E4ROKt4Q==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM05HZTk4Ry9Zb0NIWUxH
            QTNScEo4RmRXTW5CbnRwdXhEa2g1THhzSkRjCkQvWUFQQWZLNnEwVFVxczJ1RHZC
            d3JPbnI2eFBtZG85cWdwOVovdTBKVFEKLS0tIERkS1NsbWFVc2hsdjNJY0U4Q24w
            VnpXL05venRFRk1JTTNsdi92MTJXUzAKz/jFRdnlK+4PkCxSvVNiPMKqKZ+x5m2z
            MQ3/yCTJo92KPqTKa+rB9anWBpOX7EAGDDrKJjHwNiFeLmOS0LMnyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNlBuMzRmUTNreno3V1l1
            Q3JKSE1wUmF1cDg1aVY5MHo1eXVWZXBqSGxRCkRGem9ibUV0L3N1RnVoSUVkRkF4
            MDhBUXdOWVhlanJreHJwc3NrcFFsZWMKLS0tIG9va2pjbUdQRTRaYWFmNmdqdzZx
            RzN0Wmc4Ykp1NVV1dnBlRnRackxiTncK9wpDtO8OPhWVCnHMJ45DQ/Skz3Ux9/ru
            ed7a2xKB1LfcXqNeZ2crUpmUuGSmPRe/6UCY8eLwSI9z3VjwHngB2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U3VncVgzTTFCVXFjc0xM
            K1lFUVkvMzBINkYwc0g0SkxsaWQ0RFpGQ3hRCnhBK1VWMzczdGJXUE1NNGo0Z1FB
            ajdWMU9MQ0ZuQmo4R1JCQlMybEVNd3cKLS0tIGpMQ3diTjluTkhaeVNqMmZlVmpX
            RzVpeEdqcCtPYnpsNnM4dm10cW5lb28K0uWQGBnAyJ7w0RUqUZ4r1xsg8YfFEDMM
            1a+6OrODKQ4Hk2zeUXvoJf8wVpqfDxfpNxq0RvpnD0HSLGzsmqFmIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubDNzUldzaGZtTnppejF4
            aHZUbnFWdFBaaTFmZzJ0Y3Q0THRkblhvUGxRCkhQcWYwWFdka3hxVFJIWUhGd2h1
            VnJLWjhucitVcE90V2VTMm9ncGh6SFkKLS0tIEJ1Q0hTcGJtV1hSRVVpTmllMVJo
            M3Fqbjh6U0c5LzFkMGNTdFZhS21ZT0UK36L2c1DRLAc0LHoWLgJdiOTe9ijl2tD/
            uQM9ONs+YsG3N8AHy/0j7Bhyk+BssXwuYrb1Q5e02vn0yi/oN5cICg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVG05TnYxbWxHOEdOZS9Z
            Q0RZSFZVMEduNnYydkVQc3ltRmdnd0F4WEMwCm85djkxZk11Y1ZLbWtsejhacXBR
            RENPYUM3b054amZHT0JpM3l1dTNTaFkKLS0tIEhMQ2lEQmRYV0FBanlQOUUwV3Nj
            WEExKzZTWTRydmRialpKdE1PWGcyNTgKH89ExzztnJ17aC/G8Bb05IBHuCqmTry5
            2ohaA6RhrE0dKZT4pNhIO9WM6lyMHmEFlo4DdczS0fiR5R6yuPStoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ2Z3SXNkWGE2WFYwL1pn
            OXgzMmRON2k5UnljODd1dHM1SzM0YldCaWdnCnAxaEVpWjVZOHpsbXZjU1MvWHAx
            eElLNVlhWjJwdzJ4SjMxYmV2SU0rVGMKLS0tIGRmTHJQZkl0Q1BBRXp1b0x1R3Z5
            OE1ReTZIRHNXeWlpOWRKZHlzZGJmSEkK4NYRqo6W5mbPj7U0tj65YUWZbcnqvb+A
            Lz8+xkuH54HJq7oqf/xvrKFo7IF1sMXAaDy9etTVxnOBawkK2LPGSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T07:35:58Z"
    mac: ENC[AES256_GCM,data:yref4sWfrO1HxEm3Vf8O62G9QTD55JzhK1Zp7eLZdx1lSv27tlFil5gcSVBAiVh+9ZnZAzrmMe7zDYEx7becA/CZI46PA6Fa1TePIinqznappxAkP+bhmMXuJY+K/bzKCpLBLUkPte6/ANKSgVEfuxigCGfXtGRuHAg0AvWx5Es=,iv:hNWhhU+5bryZqxYv9Fi7MIIS0UYza28UbvfCeLHzf34=,tag:6q9RBs+NRF+t+IAIWHnMwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
