apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-cloud
spec:
    secretTemplates:
        - name: grafana-cloud
          stringData:
            access-token: ENC[AES256_GCM,data:cglownX43Un38SutEwMl9772TFStTWh9CSQxEKOHhw7rvLTg9GIEYNf4+jDGiq1jz4iFE+4k24cYwYEFr8d7zJKpWFLTao1KyWOIDoBGZD5bDEw069ZaT/gDH+XbJUZj4VM0QasAtNYPttQKyEvZ6CKy9sf2L5gejI8yXrk8DeDgllLP4IaRkwDDAOwcL4cngQ3g4STI+noe2SYmB3nIffiPXIyISHykbVhtjLoX/WNHww195R1CJitrbRuT0fdrZHv6I/+59HLb/ypVkH8EX1eesCcb56p2,iv:jm+zWGPf9GIIwN9CO7X18puDdZwhiPdmxHxIN5mXEkM=,tag:aNMpa0w5H4Ft/FfrTPkpuQ==,type:str]
            fleet-mgmt-username: ENC[AES256_GCM,data:bQ6OuXleVQ==,iv:k+cG40imTQrqUyIAJ7Lb2QA0/i3IMKDVen4wwSga2xM=,tag:hYRxrZjBe23Pcl0fj7IrgQ==,type:str]
            loki-username: ENC[AES256_GCM,data:P1AhIpwG1g==,iv:snx4d/71s29UU5FpAfvS3Y+nalWW5vAJYqVtWd9DRd4=,tag:JZEbS3BO1Gyuktgy4vMpeA==,type:str]
            otlp-username: ENC[AES256_GCM,data:KrxSDMJYpg==,iv:+uwNaUg6KFEYgU6ZQTYcpvYYDFZaPH+5Mi6tvDY+6uM=,tag:HWBS15wjczjZtM41s7Ybew==,type:str]
            prom-username: ENC[AES256_GCM,data:F1GykxmXrQ==,iv:UOhdbtbO8Ye54HOLQMlnT7JrXnUvUjxAdmgW6D1bTjY=,tag:nyRHxzC1P9EeX1E4ROKt4Q==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK0hzMjZla3ZRMXpGeDNL
            TjdXMEk0cFllT3pYaHZnM3F4SG1WNUpQb1hrCmVyaEhrQS9rNW9hKzY5bEt2d05V
            SzVMTVNQRDZKT1pXaUVrM2ZFOGVmcUkKLS0tIFpiWUlUdG1wcFZmSnJYeUdWeTBi
            WnZVNXliRE5IRDg1K2tmMU5qV2xwMW8KggssrlkQRajuxkn4k7Jvt5ZTR0gzA2/a
            3IiTtet9HZHtozT4f7yFpfx1soARSRjbvCwuvknRsoW8+zbm5o8+TA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NmlCS3RqOEtCSVdLUktz
            T0VYNzMzTXkyMUljT2MxK0FDSXRINEJvQXcwCnVGZ2dyZENnV2VaVHR1dDk1eFJj
            YWdsV0FhVmtKb3Q1VFJjdXQ3cmxrUmcKLS0tIDhUTGdlUUwxRUtpbW4xeVpNQU9C
            Rk5oOGRIVFhXa2NJMjk1cDk0K1VEK2MKjIItW3AHJkVQxh1UgJXuZuQCglEv6bkn
            toUAv1nPfg4ZaveK0rlqU4VVtfh8F/suIVh0+HhoqI3EwOI+rPskOA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd0F2WG43R3RPN0FIUzAv
            amNDUVFhNko2cHlwME1qUG9MaUduRUxhZHhFCkN2MU9raTg1WlpmM24vOFk5TG5m
            ckxtbDFXd0dmYitFUDVBdXdKRGZGRXcKLS0tIHYvYnhCbEZYNk9POWU3TW10U2Z6
            bXU2bzBRV0lNTS82Y01tUTBoUkFDS0EKCIvhdVrnohDWhFBCuKJVbUZS/dnKLgSP
            TujHc8tGxlLgK6BvAw3KxfXtqTmk19KnU7LXUAn8ydN3NRXMCwgpPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc2hDcCtCR1pFWmpaWjBw
            Q0RLZyswSTBJOXByaFVieUhrcXNxanV1VUhBCkxVWXlyazZqVmIxNEYrTnVVZDVG
            eGNIVVAzejNzTlVWaXJEMDZYcWc2T00KLS0tIHZiUG54TGtUZk1OellqZU9TL3VT
            Y0w0NzFoMXFSOUxyNzA5ZVNyMWdQMTQK7BqccVvnAC9DYKx04kun12OIjyXqkwsg
            fKurisEWJaV20k3b9JwaEoiRuSkpteIkoJGD1Jki9hLrPw5NY+JVsA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnR1BqYnVmTDlnMVoxWk0z
            UE9aL1VjMG5CTWpSeHJzSmJzaWZLSXBpclZVCncxQVl1Uko3b0RQYTRrWjVyNjQy
            aWFxT3dPL1FwblNwcnN6Q3hlczdGcjQKLS0tIEhmWWhHVGRXOVVKRzdQQ0QrM1N5
            KzMyUFd0cEhmSHFqVW5LNlIrc2RLZ0kKDi5H2r0cNGLWlcddeuxzpsqyCoRM078v
            Ma5kMKpno6B5mpv+9woezgF1rD6T6fOQxa5kMNJ0EMi6ba8feehtTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXT0JBN1dNM1JPZnZic0Ro
            ZnRlQ0xiU0Mvck8ydDJyRzNqUk1KK0h4RlhRCmhjRzg5N2NBTGFNWUh4cU5YQjdp
            RzMrY1ZVYkJHT0N5a1NnNDdyOUdOdEUKLS0tIDBqYUVqZmUwZjZSdEllNHZRRFVr
            VDZWdWdISWtlRGZnRzI2S1NxKzBBcGcKY411NWety+7x0avNmpkOQlyhIs3Q9cmy
            SDRA7+0//CDFLzi2vl1Q4EbjuKpKThpg79nGjkM/Q3sXkzrTO+gvnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraDd3eXd5cDRtUHhqV3NY
            QkttV3pXSkE5UkhNNFdwQXlVT3RxcXdOYUN3CjgrL3huV0ZwcTFJb3RCSy9VL0R4
            d3RQUmZNUXNINkZ2SmVheWp5V0dVRWMKLS0tIHVsZUYzdlFNZ1VxK3lzTUsyaVNm
            YkttRGhrUDhrRFAwaVl1eGQ5WEQ0ZGcK3FZpojw2vbiFGWTJRK+37MfAxBwmaL5W
            3wxPSJhHH84lk27xMDyg1d1Ry/waUHQsAO7fuNXI+3Ou1+DEJk6oZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-16T07:35:58Z"
    mac: ENC[AES256_GCM,data:yref4sWfrO1HxEm3Vf8O62G9QTD55JzhK1Zp7eLZdx1lSv27tlFil5gcSVBAiVh+9ZnZAzrmMe7zDYEx7becA/CZI46PA6Fa1TePIinqznappxAkP+bhmMXuJY+K/bzKCpLBLUkPte6/ANKSgVEfuxigCGfXtGRuHAg0AvWx5Es=,iv:hNWhhU+5bryZqxYv9Fi7MIIS0UYza28UbvfCeLHzf34=,tag:6q9RBs+NRF+t+IAIWHnMwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
