apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: adguard-config
spec:
    secretTemplates:
        - name: adguard-config
          stringData:
            url: ENC[AES256_GCM,data:wM4U6uS9kLLdoF5Y1y0Opc++uKxY9XOXj8wvG96X41kRibua9MnZL/5wUm2HiGvzf/LFp1BZTvMjnmJmdg==,iv:yAp2q6c4Ek814Rz+PmMpuW5M+00f3+XyRQ+WdpeU+WA=,tag:8zIpRZ5JjjVn/oijtrTvuA==,type:str]
            user: ENC[AES256_GCM,data:YDgg0c4=,iv:RrlAbJVoc9wjtyJNcBGsI7uK+2oSNIXzVCuXq0DgK28=,tag:nTqQ5AXYT03nM1xPvZF9yA==,type:str]
            password: ENC[AES256_GCM,data:fPQndyr0JoAFNkCJMMQ1+NoT7w==,iv:kkuXJljhlHCjzwRBX+nrzhFk+q1X/AZuv3LrKsQUoQ8=,tag:D+cE84y5jmqXvETTss52tA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUlUyKzQwQlpsc3M1ZU04
            RmthSzFaZEswQkNPYThQRUFPYU01Q0llNzIwCkpvTTFrdS9DSkRiYkR5djVsaHFP
            bDE2VnJRb0tlUmt3QkNNSmxNQTRKNEUKLS0tIEZsdndPUFBJTytQeVZuWVlZME4v
            M08vaVcvaE9qeDRWUjMyNHh2TFlRVHMK/qNkb+oUGQeGDzA9+KSqda8/jECCG5CI
            Cob04ADOd84L7XjDINj5GJFT3FlpJZDjHSsA3J48IbqW+7I7ERH91w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWG5zSW9ZNHRiMFFVaFpa
            bXpONHQ4VjFvcElBeEd4L3BXWlExdGd2Q0VzCkY5SXpja04yWnJWY05idnZPaUZO
            ZFFuMWdpOVR6SUF2alp2NkRuN2JBckkKLS0tIGVIMElsQm91MEczTGdWNjBwY2Zl
            a24xZ3pFRlRFSkJML3ljK0JjK0R5dGsKbusQs7kwcZws5Z3P1B3m8HcMLTjPxgAC
            SeGHHuh1AeEx5I7t9XjmvkfNqyXBxs+2YsqatbDZ6N57DMSjoyM3qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnUjJyVlpvQzRiLy9RMjNt
            blNnZkJhNjQ1WTNWK2loL2RDNGhSdGpsdXpFCmxlazZTM2hnMENvN0x3M2FydG1G
            Nk53bFRjTUdlWU81VlZpNVZWWjl3NzgKLS0tIHJ0eEtvbHNCb2x0bE1IemNGN2hZ
            YVYzL0VYWE9nYUwwTGNuakYzRVJSR2MKY9X709zEToSvamjnFgb0TdDd4tgYNHX7
            pNYHbzvYyQNfnAm5iHNWQgOfw/SoTr/vY7Zod7LqiFkV+DMVME4olQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwclhsWk1OdlRhalFjQ2M5
            eC9lc3NRQ0xCOHRwaFVpZXgwV2hxeGtySkJnClFXK2p1OVV4Mit0MjBmaDhjM0VN
            Q0g1dDN2akhDTE1Ec2ZyUXI4SnlFSVUKLS0tIEVzaTNXVThtcUVWTEVKcUp6bTVC
            Wm9KNlVEbHFLUXBscE5PWk9SWXplblUK4Jsv6HhfVbtno+FBsM8Tf6IDqlh9IFc0
            qzkT39DfgrNExjVUHSWMI1N3LO00vN5tj/SyUlJQywQ+MQzCZgWPtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4a3lqZkZ4aVNtMDBtcE9G
            a0lKVEZybXc4SE85cjYrNWJ6Vml0K0ZCNHc0CkFGMW0zd1h4Sk1hcHorNGRJZEM4
            bm1KaGhwdjZINFFVNkNWOEw5dEpUbkUKLS0tIHNDaEVqZFBJTUM4V3E2K1duSmxM
            UzdVTEtKaEdyaU5sWGc1SjFiMEdWRDgKy2i38sP7lKpTcKzCtM6TTjegHxTpjDRt
            svKHnimN6hd5ZTL8IUeNamR/F7hnb5DimCT7uuBbWXde99tkYmuvcg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR3h3QnZ0VE5EbG1GSVFC
            bEdkckNCekdjRGh1QVE2Tnl3VGlLcXhjcG00CjFqUnhYaGZFOWNpd3JuMEdYbFht
            cGp1MVV3Y3E0ZjlrSlpBSVY1Y0d5ODQKLS0tIFFyVkErK1NSTFlFcldubnBEemZp
            K0grS0EzV3ZmcTU0L2NzUnV1cHlTQ0kKe58wKiIrs0q0Uxox9coOc9kqlgVqIfsr
            Qa05zQVCW1zBhsd809qQj3w8c2X7ITBa+x9nv+TRDZN4v4vGKUY5ww==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVWtFOXpia3NCY3dpSDNE
            SEZxczB1UkJMTGZPTTV5RDlLRGVzM0UzeGdvCnk3TzVDdkZ6a2hVSlpkYjN3bjRF
            UXZzZWZObFVkcExVNVRpUjIvZ1hpRVUKLS0tIExUc1hzWVJTS3pLZnRtSmpOb3d2
            TmFwRnhJTm1tSnV0SU85cGN1SkpiSnMKkp9ll0ONXwmZAhBybkC0FqS1Qt+34HzJ
            vGIK/QQpEi24ddbZ86LdGHBgzxBxwdM3520ZPgDaIkL5sB80ffQNbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-17T07:33:01Z"
    mac: ENC[AES256_GCM,data:I13RnWiOV8eLDGaJbOCJKmEuJcDIc8BomSEGlAdrMH1wNf/dAFe9AbBqQnx3fJFpgE0MSl/MnXLi5gOQnxxYLS+SerSbueygd74vvO6Kx/77ZlydrNHncOenabfRA4veYjWb4ZRE0y4jGJfnTfQu/jcFpFskRWtvlIXoLRNHoHA=,iv:UThj6Bpo0pabvmA5j+R2lFAcnIXjkz6CGuvuEEs9j4s=,tag:t6bD5cb3r/Di4Zyk7MYiMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
