---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disconnect-2022
  namespace: disconnect
  labels:
    kubernetes.io/ingress.class: traefik
  annotations:
spec:
  rules:
    - host: "disconnect.paulynomial.com"
      http:
        paths:
          - backend:
              service:
                name: disconnect-2022
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "disc.paulynomial.com"
      http:
        paths:
          - backend:
              service:
                name: disconnect-2022
                port:
                  name: http
            path: /
            pathType: Prefix
