---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disconnect-2022
  namespace: disconnect
  labels:
    kubernetes.io/ingress.class: traefik
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/appName: "Disconnect 2022"
    hajimari.io/icon: "mdi:calendar-star"
    hajimari.io/group: "Events"
spec:
  rules:
    - host: "disconnect.paulynomial.com"
      http:
        paths:
          - backend:
              service:
                name: disconnect-2022
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "disc.paulynomial.com"
      http:
        paths:
          - backend:
              service:
                name: disconnect-2022
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: "disconnect.home.lab"
      http:
        paths:
          - backend:
              service:
                name: disconnect-2022
                port:
                  name: http
            path: /
            pathType: Prefix
