
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: disconnect-2023
  namespace: disconnect
  labels:
    kubernetes.io/ingress.class: traefik
  annotations:
spec:
  rules:
    - host: "disconnect-2023.paulynomial.com"
      http:
        paths:
          - backend:
              service:
                name: disconnect-2023
                port:
                  name: http
            path: /
            pathType: Prefix
