apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      targetRevision: 1.94.1
      chart: tailscale-operator
      helm:
        valuesObject:
          operatorConfig:
            image:
              pullPolicy: IfNotPresent
          replicaCount: 3
          oauth:
            existingSecret: operator-oauth
    - path: kubernetes/argocd/apps/infrastructure/tailscale/manifests
      repoURL: https://github.com/paulkiernan/homelab
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
