apiVersion: v1
kind: Service
metadata:
  name: k8s-api-direct
  namespace: tailscale
spec:
  clusterIP: None
  ports:
  - port: 6443
    targetPort: 6443
    protocol: TCP
    name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: k8s-api-direct
  namespace: tailscale
subsets:
- addresses:
  - ip: 192.168.1.200
  ports:
  - port: 6443
    name: https
