apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
spec:
    secretTemplates:
        - name: operator-oauth
          stringData:
            client_id: ENC[AES256_GCM,data:nAd3K3rcHogR25mG5E3LgjE=,iv:hY3Uuks5lUC28tkQTOge3/w9IEhfMI6MI3lJu2e4rhs=,tag:lykpnKJUqsgbASztElBoWA==,type:str]
            client_secret: ENC[AES256_GCM,data:JdLGTlOMPf4AHkdspl6oGhNVv/q9uH96FH3DPGpvxHEG8dXZgMq5Ne1jSuMyuibx5obYhaGRFOzmUAnzAQfaKA==,iv:TEnKOlyXTgz6Zo1twqvAmlw+Q14rs+O1mLn2Oit3nW0=,tag:c77QAlPV0bIHWg4H24XWJw==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRjNOVXREWEV4NTcxdktT
            eHJnSkwzSnJzMzM4eFZINTNUVEE2aGRiYmd3CmZkR0VpYXYycGJWcTFRSHB3M3Zu
            eXVsc1lrRHBkNlRDRW1ndFVyalJQMncKLS0tIGpJay91NElHdWpBOHcxaFRHZkVU
            b2ZVbGt1eUlqMDIxYnR2eURlRFJVdEUKIHXpE5/TkqgdG3XulgiVop8WE/ZTmNxU
            xfoq2m52Bifoi69VgGztSKPbH4v2BIchcq6djO22rSRdKb/FWitcSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMUFva3Rkald2R3l1bXFS
            NnBtQ3RmMDdxOGhqYXhOcmRPbCtjaDBiLzJBCng2WEdHc0UzckxicW5yYm9EZFo2
            UXNXM05ETmt3WTJUa28yZ09wbVd5eEUKLS0tIDNRZHgrM0hoK0pyNkYwSm83WWsz
            YXVqbzVYWHFBVlRaSGxMN0hvZ1dCQzAK+bgKBDUkyZiQAtgk9YKO4a6vX4NEOdLe
            TSEcRV53Ym/ShH38C3a+4t+7yjgBZScgHgFUSny1rqqjIGaDHggbvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaC85ZG90YXlNa2dlUEwz
            VDdHbW5hSUhXeHVoWGFnOVAyWVo0MFRCL3hjCjUzVXNYRURrOXpmU3Z5WTAyRU10
            NmdxNE00V2NsMmI4ZmFtcFlVRDdRbUkKLS0tIFR5YzZ0M1pCMldRamZONzRmK1RW
            VFBLdUliekk5NW1pWDdKbFE1U0o0RUkKvCb7AfEzZQczPc1P36XWKeUn3LzQ56Jl
            n+AvcbiHXWdpYIXALQxJLuXQv0Ts/uOwHD93qU/xSAEV0WuEzQygMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmL0g2OFRsRVNuY3VkUnBI
            Z2EvSklVVC9oYnIxR2liam1YUTM0Nk9Va0RNClRPaSt5SXYzbXFqZjdVVmErUEZa
            WVBEdklqK0h0ZmtMZml6c0pvdEYxejAKLS0tIEVncFRteGhqMkxabEZzdjBPZDBF
            MWhHZGpVSmJZWFVvcTRtWllER1ZaeEUKwdqlGDPt5FNg7gq1j4BjEhH8rFqS05eC
            /ZY/DgLpNB7Aj5Pveg+8ZWCr5YwSBcBWFm0QbeAjaAuW9XbOhib5JQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YnpyQnA5OXVQaXFlT2JI
            N0JmOGw4T01jUGp6YUJMeFJJY0RoZzY5NGdBCkhaS29uaXptMlE2bzhkSnZQQXpD
            S0dPR2F3eDNYN0dneDZDbjlITDhVR2MKLS0tIGk1NUZDVnpUTEhFckFYT1RQNW9Z
            N242V09QUDI3eU85UEFMc3draVU4TlUKjIrSbxNpJrqbv78g1sMcJdhEPVp1+oLE
            ksOyRTGkJUoGf4cj+hE9LNvExATMKrgPi8tOPqGnxnD9gnIEM8zGsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM0psa1dVVk9NUjMzQ1Bs
            ekdaeS82TnFJdCtJeWZJUnU4NW9XMDNpeG40CmExSVJGZEx2ZWNabEE2YzdDcjBi
            NFBQaHFkRVdmMC94QWxwYlFjTy8xKzgKLS0tIE1jSjhNaTVXSTB6UVZtenZUbDY0
            djRQOUNJaWtOMUg3a1dwa09YZ3NlNG8K79XKB3Imqq6tW7MwrtFcfMsGU/aV56LA
            0c9MuDPWgZrbj0C3rs8xKxQhEBr7AKTOJ4L9EMxydf20eGqk+uts+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDSktNaEpObkowck41ekh3
            RndSaE9oSlpjZlJHZ2F3aFk2bHlKMFJkcGhBCjNDbFNMekE4ditQcGVOMHZEbG5I
            L3VacHJWUklaTmRqbVJmSVpobEJkQTQKLS0tIEtNMWhQUGVyd09mU0ptQmZOQ2xH
            T2xnRWRSNFFwZ1E0encxOGpGOHJ1cWsKfoMefp73g+3yLm19wBydzP+09lLcJwuW
            wLcMHt3wypGZquPAkck5CDV0XV2mTrJG2iTsx+5IWpljjEsF8tWg2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T06:28:46Z"
    mac: ENC[AES256_GCM,data:7e2w2kjUfGJUqPHcUhUv9U6GemkpmLUJCukB+k0f7I4bIPOMtDeW07NDMB2MryQX5nrdiwUiY7flttJBPgwCqjeICbxG8U3XLOvx9eyigfFbw9xrmepgb/aEdqQ38jCs0rywzdwTPmQgjBQ/QNp5CAJOCh0kthohukrkpXJ0M6g=,iv:CZkDx/gWZgUofT+gyy5VpRYdAXcUFNnB2sfagbvnKDw=,tag:03oKL6vAnDGFTVXFFZozuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
