apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: operator-oauth
spec:
    secretTemplates:
        - name: operator-oauth
          stringData:
            client_id: ENC[AES256_GCM,data:nAd3K3rcHogR25mG5E3LgjE=,iv:hY3Uuks5lUC28tkQTOge3/w9IEhfMI6MI3lJu2e4rhs=,tag:lykpnKJUqsgbASztElBoWA==,type:str]
            client_secret: ENC[AES256_GCM,data:JdLGTlOMPf4AHkdspl6oGhNVv/q9uH96FH3DPGpvxHEG8dXZgMq5Ne1jSuMyuibx5obYhaGRFOzmUAnzAQfaKA==,iv:TEnKOlyXTgz6Zo1twqvAmlw+Q14rs+O1mLn2Oit3nW0=,tag:c77QAlPV0bIHWg4H24XWJw==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMzhVM2Q5THRYZ1dOZE1p
            c1JET0xXbEpwb2VNdUZlZEFMNHcyV3ZLSFVrClZ5L3FkWFFBNllpNXowQUV2K0l6
            K3VxRVlZUmdNdWhLQ0tlVkc3YkV3YXcKLS0tIHJBaitUalpjanZyWUlsT1I2SDd6
            MGxrUXZ0UjE5NkVNM2l0SnRUYzE0UVEK6wPXZYREQSzMy6N+JzrXc87r6kYCj+b7
            qfPu0Ztn+msIZnu8S610VGpmiM90XcoVvhKjSqFIGKBM/tSeZKYuCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaXVSaG9RcVo4TEtQRXJ2
            WHNYUjNxSS9NNS9oaW9OUGFFbE9qbWhMeUFFCm9ZakUzTWJPeXFGajJRTW5HVEky
            TDQ2QVAwMzdDbkVSU2RWNytDNGw4cWcKLS0tIGhwTHQ5VW5sVktVRWpNVHBXMlhi
            RWUxSEdrd1NscXNWZDIvREcxcWR5SFUK5wcEVC0ClXLduS0pXSamgwJhS92ckqWS
            NMeYGUWmbZM1m2+QfFVMfL3xv8MqRyrQBUe6JSeYrQfHuyov/KgRqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbVJZcFlnR0NGWnpla2Vv
            RGdZSEpQM3JKalh1d1pLMkhObjRCRUxabjJBCktGWGhXYVcwMEphdnZzdDl0TFE4
            RkxzUmRKQVhYYnRMRVpndnhyOVlOdkEKLS0tIHdTd0ZEVG1VN2JTaWpZZnhkYXZC
            NElRajZrc1hXTmZhOGZEeUk2aGwzbnMKt5OODlSNTbzNqESy4DpOCo5JLhMtCiA0
            +7Nyx1ubrv4GEVpPn3n7H6Co/2aYC4IJlF5eLs8O3doVThruah0QqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Um1WZ1VJSnlPQVZZWHFK
            NFcwbU5jRVM4RGpuUVJld2ZSZExZSnNINWcwCnh3N0xmUWpWekNRL2Y4eTZmZ2lD
            bUZRUkpXOHFHUHFoWmVxbDFidFhCZkEKLS0tIGEvNWp1M0lDMXUvdkMrMC91eVdQ
            eFJoZ3lHWk0xaEVreVlHeXRMdW5wREUKCBmKHznjpkMPGVnriQKOZjim3ZNW5UzT
            aHXf5JI7EechlZEHL8rYIVmmdPXopRL7HaEVzZ1N07p3CV9LZw55yA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzenZTOVFKZlhQQ2pNQ2J5
            YnRzOFRtU2VJZlpnWldhbWNwOGx4V1g0SWg0ClcrMFVnZWowMm1OSTEvWHNLL1RC
            ZDV4OUhGQ1pvZHk2M3pCSGY1a0JNMjAKLS0tIDVIbUY4Nk5qWFRGR2o5Y0sxM2gw
            cndQUUV3Y0FVUWc3aXFxY0h0VXlHQ2sK2K4XDzPKyIG6D9hkj4aeYhqIYPugVctC
            Yy/gb5lnQ2ASgY44k07sNqwEw0khx+4vahnHjFmSSrbNYreFMMs02w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZXZvNUc4UGlEaHdRWHR1
            d0pxYlJNclFlUkQ0b0NtTGtQeGlSamh3eG5ZCmF6cG1LTlBGM05TQndleENNSnpu
            aEZHSnNQbEhLTzNOS3hsaTRQYlVZMEUKLS0tIGhBNDB3S0ROcTdFUUJpSUY5Tkdv
            K3JoTE9PNTVkWE1BeG5XdGtpWEdEeVUKcF2MGGSvkIenuEnlSbRcvnk/aDyIkTBg
            3NZfBLjFMXyxRqLa4/nwmY0koPRyZAResoH9U42g1kLpyYQg4XxI7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-20T06:28:46Z"
    mac: ENC[AES256_GCM,data:7e2w2kjUfGJUqPHcUhUv9U6GemkpmLUJCukB+k0f7I4bIPOMtDeW07NDMB2MryQX5nrdiwUiY7flttJBPgwCqjeICbxG8U3XLOvx9eyigfFbw9xrmepgb/aEdqQ38jCs0rywzdwTPmQgjBQ/QNp5CAJOCh0kthohukrkpXJ0M6g=,iv:CZkDx/gWZgUofT+gyy5VpRYdAXcUFNnB2sfagbvnKDw=,tag:03oKL6vAnDGFTVXFFZozuA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
