apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-homelab
  namespace: postgres
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.3.0

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
    shared_preload_libraries:
      - vectors

  storage:
    storageClass: nas-nfs
    size: 50Gi

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

  bootstrap:
    initdb:
      database: postgres
      owner: postgres
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vectors;

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        passwordSecret:
          name: immich-db-user
