apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-db-user
    namespace: postgres
spec:
    secretTemplates:
        - name: immich-db-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:sMS6ePEV,iv:JT54eNqFFaVruNzxA02qmvPfIYEHN0mlm3uiTw2N9XU=,tag:h7k1I11kpJx1Wwc2B0dT+w==,type:str]
            password: ENC[AES256_GCM,data:sWifwxmN90YMhXbG+CApWVnH0a6ulYqizyj4XWxgXg==,iv:iDzvpYO3iJC7r+Mwl5OcCCEMC+A+ovT/Q7NPvkCTlmQ=,tag:vdyJ3y2iwBQtq3q0sMqHlA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTktwd2N3Z0tKSEpsUHFE
            T0c1VStIOFRnTFVIMU85aFhqbHVubVkrbVQ0CmdGS0VZVERKMG1kTEdEdGNuaHI2
            YVhSaVdGeEhIT09MSTR0UGhqNEpDNlUKLS0tIHlVaGovRUx4RGFsVDl6cTg0OEZZ
            dWFscVRDRlZhbHNJenNibmpUQUVMZXMKOTnHtF4do1ADXwmTZYJw2Ed1sm8eG2P8
            f9N9cxA7NQ2fv52kjzeW8Iy682JAO04d6Z+GS9R/XA/vI+SVg72fog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQlpQUkVLdVRWbkYyazA0
            NVZlcU52TGhBZFI2bHA1Y0UrTjh6TnE1T2lvCjdScmR3NG1KR0Z1ckdCMTFRZzdL
            b0htNHBmZTRtMnRybE1jZ2VCTWY3SzAKLS0tIDR1RVBBK3V5L29XQnArK2t0SUVj
            MlhxOVZnSml3NDIxS1F0KzZtbmFRSk0KSlaHVq4Sp4pphAPT3J750OJfOudeYSzb
            ZlmxZ2Xf/A1e7Pkmee/11Ikx930Ew4ZglLWTOEqtwEFZeckHz5PXIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdjJQdGJyT1dsR05QZ0tO
            UWhDWGVRd05RNDNiMUNmYzJvWS9NZXBjY2dJCnJKQURRTG9Ic01xRDI0OTBHaXd3
            UVFOZE1WeUY5akZLdHZZVW1rMUFzcnMKLS0tIG1jNi8xY1duS2JhaUlxdlZhTHh0
            Z0tVWG1yTXV3c1dmMjI4cWI4aHR5YjQKKgctBHVHVxvR3Ea0/7bRAVVhnC1IvW1K
            CQg+WTe17pGLe+odm9upTUuiIh/kKAnQENOd4N6m57BxATVm2QSoJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MzNOdlRia1I4Y1d5TUV2
            OVIzbXBWTW51eUcxYldRWEtObHM1QmZTbW5vClFoWVZBd1draElBWDhvU21Cdnl4
            d2NwMlVMVGZjTlg3SE1TVzF6WmlUWU0KLS0tIHozMFB1WmFyODdwWk94L2dBTmpT
            ckYxK0daVFRKeGN4bFcrWmw3MGI3N1EK84COcK3tWXtnaP61aYOxenO77No6Xbiu
            5zAeXYnO6pjYKrBHUIfsMC2U+chVfjthWIqu4psvT5OGTMMsMn8n7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OWtsay95UUxQTFUwaGRT
            L1VOdXNRQ2VmcklwbTF1RURabnVvSzg4bVF3CnVTdU16M2lxWmo0UEQwUlVab1Rl
            TEltSUE5aE5GeFhLbU1tOEVhYTVYdTAKLS0tIGRnU3gweFNSZDBvYzlrVzBBY3pw
            K2IraXJWSytzRkY0T0NLVHc0d2ZPaEUK+nWY5qyhEIfZg0nogLCHy9U+uUXCVGUW
            DdiF1r2Pru0IW2/F8sZsWNJsshC8Rf83ZpEwhFo3j7Mso17qlenYjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVE8yZ2pkM3Z2S1RESk8r
            bDVuUHAvdlhsbjQxeCtTRlh5dkhLcEhTemg0CnNIN0tkTStKd2syWTZHWW9jUXEv
            WHBZUHZPcGcxSkJqcUg4MnRvMVBwaG8KLS0tIDZERzR4Ylk1NjdnQWdQSDFLbzZ4
            QmVLTkwxbjgvUnpmS1QzdW82TVhRN00KDpmrZZqM0d+wH6zNiRVofg5tEUGjciWA
            sbILP06NqtKeKHJU5vRC70dV3CqgXHNMJeRU7yCv6nQIbeGO6rGhkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T22:04:51Z"
    mac: ENC[AES256_GCM,data:AYha1xuufvuyD9BapF1ztgZRVD1b2+1fcF+zJWeZdvJ5HBvPl4a9N+GoEGjowuXQbV7JfSPVXHb1/d2ObJdkoQU9AHjdrrvXxy5Sr15SAJvNJIWrN4Rws011zM4YtI8zq64kBkQbn5C307bsoQUZRXlc2H5gPZ/kn/M2hGz/77I=,iv:6rvUnExxKzo1L+3u53dyizh7B+XBUZd/v2vLomgU8Rc=,tag:fruScAUDnYbv32q0jrUrUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
