apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-db-user
    namespace: postgres
spec:
    secretTemplates:
        - name: immich-db-user
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:sMS6ePEV,iv:JT54eNqFFaVruNzxA02qmvPfIYEHN0mlm3uiTw2N9XU=,tag:h7k1I11kpJx1Wwc2B0dT+w==,type:str]
            password: ENC[AES256_GCM,data:sWifwxmN90YMhXbG+CApWVnH0a6ulYqizyj4XWxgXg==,iv:iDzvpYO3iJC7r+Mwl5OcCCEMC+A+ovT/Q7NPvkCTlmQ=,tag:vdyJ3y2iwBQtq3q0sMqHlA==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKalEwbWNkN3FGNmFWZjZk
            ZXJLZm1qM2JiUVg3cFZZVHkzNDdMdHRVeWs0CnJtNjhtdERzRitXa0ZtVlRnSzlv
            SUJFM3JHSjN4YnpUclRHeGliV1h3K2MKLS0tIGpYUzlpUjNQeG81azgrdEFCK0FU
            dklaYXV4eVdoaDF0bEVKQnpyaWwvUHcKlB6Lpa0dl9raaqs1h6ySk04YhVisBwkt
            y1BwiPWyFYjEmm0H8otDHVuYnRv6JXWQfDMG0Ll9Xqtz3Qr3BsVbPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcGpaZHByRXpuVk9Ielcv
            VHpyMkRPQ2V1RzEvWFZ4elFBZFVzU0pCSzBFCkVvQkVtQUZ3MjBPbVo1ZFdlVzNq
            TC9saFMrY2x5TVFSOHFVUHBROWg3TWMKLS0tIHZIOGd1QTRKVm9ZblIycS8rK2Np
            clFVWkh2NmF6RStONmlpUVZOR3F4UVUKdK2cgEnkOA+WFTpPdkCjtWmvSH8H0YCF
            70JN9QPEZPMkpWYnMbFdDc086ZEJKbKZog9BsLE48kZX0jdSeSst5A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRzU1cnVDTnRBMFpVUnpR
            ZHdsaWk3Z2p6SWZhQ05NZlJ6YlFRSEJuRWlFCnF5VlZnTHl0TDFHU2kyTkgwcXNq
            S2hhTUN1bHByL294TEFvSVhzZHpFWTQKLS0tIExudUEvNmprOW0xVlRZZFYxdENV
            SlZTY2Z4NGxjd0Nvb0QvKy9oRVFhancKY/mJcJm/+kH3qxwKxAFuxZHGhAV7Gbh+
            Fu9xUv/noJUQ8QGrD1tpdrJQkS///+Nd83gjvGg0zok/kytkC67ShQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRDh0ampEN2hGSjVIVFds
            eHNTVGFwNURZS29sSHVMNmlQREg5VGFwSUdNCnIySnVwbFFyV0N3ait4K3l4L2pK
            SmdzKzdXc3lubFRabSs0NWZPRDZIWTgKLS0tIEVYVGltQW80Y0tuUmFJNTJDYUlX
            dy8yamcwTzNCZzlrTENsZWNvbFhMSEEKBPohrfOKTKKLP2Sj9Balb0Re3wmGq7A0
            Kjtp+tn0RLOlkjxvxIc1UNU3DPKwRmDg3uiXA6K4Rt18ljKJAzWMfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcmlIeWZuWWIyUlY5cGpT
            Tkd2dGVDRjZhc3R1WE16VlMzZnE0SXhieTNJCjFWaUNkbVZZMWQyOW9FcllxK3lV
            WlV1U0RMRXJNM2NKbVhnUE1yTmt0a2cKLS0tIDBjdFdxYW4zYTBobUM1QVlCK3U2
            UldHa2FZSFU5L1lwM0twTEwyUjgxdTgKP4nNAW2DyFXA6HxKRPo037lW19Tsphq7
            DL+yMI/+YOrQn1SABAM2M61K7yHZziFVdjrIEuUgldGhUZ9naNefnw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOENMMksxUytaQ2RMNEtV
            WmluczFlL1RyTlBkWnVTTkU4NVNwa01sbTFBCmhlbUpqRDF0MmNKRnVqdlRUVmVY
            cW5KaEFJV0lHWmlCSzIyZkVxa1Z0djAKLS0tIHZYN3UwN1A5Q0FjQXdqR2VheUx1
            VWFuTVJqVlZxbXFCT2RIWDRKSVRIMUEKZU/atbly3PR20zRk0DgZWKF20a1kWqi3
            LOigwHPUgJ4Dkl8251DvqM28X1euLa/Zsq/FWktjE5tCz4wBDuOCmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WFNtU2hFUWsvZk5zNlVn
            WHdzNEJ4aVdvRmg4akVoWDBYSE5Ic1VwR21jCjFsV1JST0k1UzBqVE1RcnllRFlq
            Z0l2YSsvbmZhWU1SSVg4MEpTbGlDQTgKLS0tIE1yODBSZGZvbEtIeXowVDhzbzUy
            ekJrWEt2R3R5SlJuZlZDZ1dwS1lKV2MK692jKSQJ3S7O8Jgbor89PqUqht+6qC65
            YjsRyxEFTrrzyTLbMy24YBdwkqg2GDf/eVwlzuajT7UU6oWpkG7N6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T22:04:51Z"
    mac: ENC[AES256_GCM,data:AYha1xuufvuyD9BapF1ztgZRVD1b2+1fcF+zJWeZdvJ5HBvPl4a9N+GoEGjowuXQbV7JfSPVXHb1/d2ObJdkoQU9AHjdrrvXxy5Sr15SAJvNJIWrN4Rws011zM4YtI8zq64kBkQbn5C307bsoQUZRXlc2H5gPZ/kn/M2hGz/77I=,iv:6rvUnExxKzo1L+3u53dyizh7B+XBUZd/v2vLomgU8Rc=,tag:fruScAUDnYbv32q0jrUrUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
