apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: postgres
spec:
  cluster:
    name: postgres-homelab
  name: immich
  owner: immich
  extensions:
    - name: vectors
      ensure: present
  schemas:
    - name: vectors
      owner: immich
      ensure: present
