---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: taqueria-bonjour
  labels:
    app: taqueria-bonjour-frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: bonjour.home.lab
    hajimari.io/enable: "true"
    hajimari.io/appName: "Taqueria Bonjour"
    hajimari.io/icon: "mdi:taco"
    hajimari.io/group: "Apps"
spec:
  ingressClassName: traefik
  rules:
    - host: bonjourinc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
    - host: bonjour.bonjourinc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
    - host: bonjour.paulynomial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
    - host: bonjour.home.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend

