---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: taqueria-bonjour
  labels:
    app: taqueria-bonjour-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: bonjourinc.com,bonjour.bonjourinc.com,bonjour.paulynomial.com
    traefik.ingress.kubernetes.io/router.middlewares: traefik-default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: bonjourinc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
    - host: bonjour.bonjourinc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
    - host: bonjour.paulynomial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  name: http-frontend
  tls:
    - hosts:
        - bonjourinc.com
        - bonjour.bonjourinc.com
        - bonjour.paulynomial.com
      secretName: bonjourinc-com-tls

