---
apiVersion: v1
kind: Service
metadata:
  name: hajimari-tailscale
  namespace: hajimari
  annotations:
    tailscale.com/hostname: "hajimari"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: hajimari
  ports:
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP
