---
apiVersion: v1
kind: Service
metadata:
  name: hajimari-tailscale
  namespace: hajimari
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "hajimari"
    tailscale.com/tags: "tag:k8s"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hajimari
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
