apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: mariadb-secret
    namespace: booklore
spec:
    secretTemplates:
        - name: mariadb-secret
          stringData:
            root-password: ENC[AES256_GCM,data:z3gvoZEQEzOxgczydMX/DBspV7VQJ4NhukSg/SNcJWFgE1g=,iv:fgkxF9PyWZ9c7mAsmhx501FBwHaa4uHns3Yia6DbdbU=,tag:ZWryHpIqjWOfr0inbXGDaw==,type:str]
            database: ENC[AES256_GCM,data:vFz68xh/bLw=,iv:+0U4Urngol7/jVDur27b7mzhK7UUmt6iGhHvTwlvqdc=,tag:XKvUbvpUgC4hHxQzZzUqTQ==,type:str]
            username: ENC[AES256_GCM,data:ko/vqcwVOzc=,iv:1ZQYKVPEvjhcD5tY5P7UvavpWnBXwIQpsV4IpxojayI=,tag:Ttq9LN/l64Qq3VBASXw5Jw==,type:str]
            password: ENC[AES256_GCM,data:kskfnxEJjQF6PCKRHnzZnsCeNTY16eX7vbS9X1l8Rg==,iv:pmAFHp3Dgcm8cbwninKF+h3ih/JY3iYxUo5/ubGpLkA=,tag:VLsN1QnvHqBf+Thp5luENg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaUJ4Q0JJdUxlK3NsOW1E
            V0FZRWNxYVY0VzVVQU1tK2hqWnVENDZxSGprCjRTWWtmcm9FRWRKK3VISk9rUVVN
            OUN4dFlSNnRTay8wMytLcmNiamhNTDAKLS0tIGczRFlUZjhSSHFNZjVzSGVVZUox
            Nk9XcktlMm15ZU5iZkY3OHExSGhNbzAKPBbp2Js1Gp2uRjWRM8xWni+/c4zkouDX
            6QUhuulK0km7YsYekvNej3rKcXf1+gzs1iLLt5zGt6ZfnQb8ArnvRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd2pqNU5oMjdPTWRFbkhl
            QStRcDJOQXBaY1N4N3ppVFJ5dVNkaUdGcHhnCmlCekNxU1QxZEJqYS9TWmpQS2tG
            OE1nSks1cDd2QlNlWHZZRitJbFNGYUEKLS0tIEtnSHVFUm5ybmRwR0ZKSnZEcTgw
            dHVSbWk2SnBoSEZlM2lmVm1FRXJHUTAK71RsFQzA37h3RTBsHjV6tJDFoknVfwFC
            nk4wIapCK66TNEU9mI8ijGDbm+vg7jkITMhS8A+dozBKrCtHIKBPQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYXJPZ3QyOGJENklka3hv
            ZnZSNDhZQXJWdmV6MlE2c3hOc2dBWVZyYW1nClhTTTZzTk55TjU5TGF2NFNrSU1U
            ekpqekd4Z2xtOHo4V3hJcTd2d0VlNkEKLS0tIG9WTXZFOU1XVWVWMmlFR3EwU3BJ
            VU1odURLY3lBZlVVUTVyK3ZqMGpvS0kKsbuPYOeOTdeRbTNskho+OwiSU4dDGmNw
            pOnPDv5t66P8nRs5dX1HqfbgIUKgrq3BsDLWjDds+u2H6CS0mAADdw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvV1RjbDlyTWdINUM4YkdW
            OEttN3ZHbFcrZDV2V01KM3paWmZ4WUJOYmprCkhxc0I0ek5PRWplRkJtU0RrK0hX
            d1dJTkxyWVdQSHRYVFRDSkdRVDdQMGcKLS0tIHlPVE94OGdRU2RjajRLWU1GdXE3
            MzI4QnZXVDB6SlhyR0NzS2Q4VG9MckkK+mTobHGFzOT83DQwN2CXWe5CC7DPUfNK
            VRTEHHrpYK6HRr830MR/Xun6ok9NcAth/xTYtz6qv9iiRA6p5WVk+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MjM4SnhBaGcwbngycitJ
            RjBrYzF0cm4wbCtROHNpMG1mV0hsdkp5L1RBCnFLRllXYVRBaHRBRVI0V2xYam9k
            dVFJRG9mczVwZHJ5MjBOTWFUakIxZGMKLS0tIDBoYllWcllKV0pXeElLektEUnlk
            MkFZSWR0SFBybURaTGd3VXlibUFCUGcKOkvk8J5gTOuxr35kakwFasMgRxTUi2Q4
            7ixIZJkv4v+AgZ3ReUfjWP+E6y+4GKSb/MQiKWShd0RMz5o2wV4yvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRnRES0NXaDZYVU0wRVNp
            OGxqSGdjeStYTXo1Um5tQ3RCWWZQTmRGKzNRCnl5ODhLc1lxaUpqRkl5UmVzR081
            VEZRVm9hOFFFTzVpVXpqTGsxQTFSdzAKLS0tIGVhUlliSjFWMjlXcVNOSnc0UExp
            bkFxVHFudnZaWVhLNGJUV0QrUzdSOE0KRbBpONPsMIK3HBkgFfooo24FG4+Ebnnj
            l9b2NzBDsGlNx79xppWAyNr29VQ00Gh8Xdntnrkwi+hn/m5iRAKzmg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQjZkOVhjSVJjelI1MEdi
            bzlYWFF5VlJYbkEzZVI3SjF6cVdyeGVQb1NzCjdBY1hraWVJWHU4TzVsUGZGOUZT
            QmVEL01OaXgzbHA3ejhHNzduTnZ1QjQKLS0tIHhCOXpuK2RzbmRoR1h0Q3NDR3Jn
            Vi9RdFdqenZ6c05HNGUwemN5OWU0aUUKtTrfYy4QCBPtcJsq6y+pyR9Ck9D5nRoI
            Jgvr2a9nMKBZKU8ojlAngBbsQfbwITQN107GMWF3v8JvvI9DRH8ywA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T22:43:34Z"
    mac: ENC[AES256_GCM,data:piRKelaHql16D6bcL7eO6EwlJPixN1wnzHDeraDsX8Y96p9ZLoeesnz031GKqbeZv8ZDDsKJ6KRUZff/VU4MzrDpGVq7fjVs66HMH7h4Y0yMQkJzrBOrcJSdNYFSVCdL4sdVAmKqCzdb1Uoq1hZpz+FusxEXVM+afJRgveAGXUM=,iv:XPR63EA9vnGIwEIj9KmLkyFlkdvxEzqIf8MtWDFTeC4=,tag:iXnNbngdj4PcQ+ZiCXFu+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
