---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklore-public
  namespace: booklore
  labels:
    kubernetes.io/ingress.class: traefik
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/appName: "BookLore (Public)"
    hajimari.io/icon: "book-open-page-variant"
spec:
  rules:
    - host: "books.paulynomial.com"
      http:
        paths:
          - backend:
              service:
                name: booklore
                port:
                  number: 6060
            path: /
            pathType: Prefix
