---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-data
  namespace: booklore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-books
  namespace: booklore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booklore-bookdrop
  namespace: booklore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: booklore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 10Gi
