---
apiVersion: v1
kind: Service
metadata:
  name: booklore
  namespace: booklore
spec:
  selector:
    app: booklore
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklore-tailscale
  namespace: booklore
  annotations:
    tailscale.com/hostname: "booklore"
    hajimari.io/enable: "true"
    hajimari.io/appName: "BookLore"
    hajimari.io/icon: "book-open-page-variant"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: booklore
      port:
        number: 6060
  tls:
    - hosts:
        - booklore
