---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paulynomial
  namespace: paulynomial-index
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: paulynomial.com,www.paulynomial.com,paul.bonjourinc.com
    traefik.ingress.kubernetes.io/router.middlewares: traefik-default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: paulynomial.com
      http:
        paths:
          - backend:
              service:
                name: paulynomial-index
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: www.paulynomial.com
      http:
        paths:
          - backend:
              service:
                name: paulynomial-index
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: paul.bonjourinc.com
      http:
        paths:
          - backend:
              service:
                name: paulynomial-index
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - paulynomial.com
        - www.paulynomial.com
        - paul.bonjourinc.com
      secretName: paulynomial-com-tls

