---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paulynomial
  namespace: paulynomial-index
  labels:
    kubernetes.io/ingress.class: traefik
  annotations:
spec:
  rules:
    - host: paulynomial.com
      http:
        paths:
          - backend:
              service:
                name: paulynomial-index
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: www.paulynomial.com
      http:
        paths:
          - backend:
              service:
                name: paulynomial-index
                port:
                  name: http
            path: /
            pathType: Prefix
    - host: paul.bonjourinc.com
      http:
        paths:
          - backend:
              service:
                name: paulynomial-index
                port:
                  name: http
            path: /
            pathType: Prefix

