---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnd-content
  namespace: dnd-player-site
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-nfs
  resources:
    requests:
      storage: 10Gi
