---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dnd-tailscale
  namespace: dnd-player-site
  annotations:
    tailscale.com/hostname: "dnd"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: dnd-player-site
      port:
        number: 80
  tls:
    - hosts:
        - dnd
