apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZFY0RGhGTFR5My9sNU41
            d0FNb3d3SC9Gall2WHNYaDd2aVMxc1V5RDFBCjdHZ2l2eFEzRW80TWNwMzFMMFJw
            ZVBITHZxanFUMG81bFY1UDhDUEZrVEkKLS0tIDN3UTA5VEsyN3hSbmVHMGwvdERp
            UFpzMlNHWnFhNUNBcW16S3c1aXpVVTQKdPn0QZ0ooTsR7iK+OB+HtQxOnwydGBoK
            ZP9JLql6qS84mAXd4iDcuCCQiwRVavBrP7icz5fQYgZHGC9ZObaUqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrY0hYQTdFOE53R2cwbFFJ
            Q0tUT3llMzNiQ010TEtxdWYyZ0RjWXJaV2x3CmlZK2RwZ0dzSEJ5OHI0b05hS05B
            RFJNdWN4MnU2cDJoRnJCbWc4aEtLVmMKLS0tIERrUHRraXBXWEpTOTNEV0htTjFZ
            cmZKRzdhT0JZTUNuMm1aNDB0Q2Z4YVEKfTiZa8S11SOf2+6HxibcXJW9l/TWBe7q
            /D9Bg/zob/+ug51y47EkStTRi0B1jIvLBmt6F3rddBkExqn2fw8w1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV0Y3Y3I5b2dMTWxJNUc4
            cklGT04rSERQZk5wQ2gxREJRc3J3QzgwTmh3Clp3bEpJT2UyMzlxbTlEblV2cG5p
            eHlmZjA1UjBGU2JGZ3NiZktvcnZEakUKLS0tIEwxVXJJZ25nQ2F5c0hsa2dGNUNK
            MDUzajJmdGdwRkMra1NoK2tIUG9nejQK1kbrKyyH+6w7K7sCJ+gX8hryeZ0iiy/v
            ANOv+PGkNx38WSowLaDLoSJDxdFGSwnWif5Q3LT5iFw6xlSyVLnK4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCOVRmZkdrU0E3UXgwQ3RN
            K2ZETTZ5T1BTUTBYYTR3QXlMZEFSVWNNZlRzCmllWktKWCthalFEemFsM3craThU
            R202cm9mVzFFSm4wL0kyaGd2Q3RGMmMKLS0tIFhnSlZmMGo4aG5jNkRqZWFYMVpv
            WitSWGhNU0Uyc3NIZmFBUHpSMW4yUTAKyIb8OFfnKcQYaqpSaUEE4BzXnazsuD0T
            5vIkYgeaQdK5AdkBHuUjx+6xoHKUjk2codYl4cvUUo0qHxr+FhJYNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZ1hLMjVCaTVaM3hBYkJz
            SEk5WEFZNzk1Y0pBTmcxSVBaazg2RDRickRZCm9rdkNQS29OUlgwVWRFOWcraUho
            cFJxTi9KNmp2Q2JxTzkxN1JiaUgvekkKLS0tIDQ3NVRibStlK3R4NVRpMWxzaDk3
            azVydkdHTHBsZ3ZOUmxWWEVKajJCUUkKpA/1Qf82jzEzYzWfQoXBNY8MTH0mgByx
            EuDDCf95QBBN6Tq5EQPZhG3YWkFSKo74hKPh18tu45d9nW9dz2aGFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T07:06:26Z"
    mac: ENC[AES256_GCM,data:XBM6eOER4lBw0W4K0nf2MRHbLgUJS9taYS6j1CZF39WxGyVKjYLHPfvT/qLgE9fvw3miH3a/juag1/w7Pe8o8Xt3I/j7HrZ3xT0w3U8hiMwlftxdtGIr2LYNyfXREoNG//01OjSv2fcLspxNanJqXSlh9S1mFhRoDtPOIKlhtAI=,iv:283lFCZFEPm6VtAukiiy+O6Gc/rp3mxFEELTyRa3e8M=,tag:YcNFUpAk4KaIiTJ6PqBDBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
