apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ""
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubHJENFdGaEhzS2FHMURJ
            ZXZHRFl4aEt1bU5wVkdKakxsRUhVcDZXSkdFCmpYRlNzT1h0c1BHdk10cUJQZ2wr
            cjdTYTQyNStpMk15OTBNN1ZyU1R5WmsKLS0tIHVUc0dOdGJSUUpRNXdFWnd3RThM
            OEtOQzErSEJ4ZU9MUGFQRWE3YmFkTzQKVrlCOtd3CcSynrJJZGR0xP1I5xJOyphn
            E5HrksYBchbbz2yMAOAxb2VnFstmrfZ/JS8G6yYsJN/jFObcUKgRTA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTGpsVlpNa1hiZFNiU3Np
            UWJObTZZeWRJaWRyRmpmaWlDbnc4T1FCeEVnCmc3TlNZU28yZUFMeEVmRlNhZTFq
            TDJieUh4dk9TV204Z3Q1RTNmNTBuTW8KLS0tIDF3UFZRTG5nUUtSL3VjRGJFMnFH
            eFJPeERIL1dXOHNmQk1WR3liQjBQQTgKaSVGoI0ixOnpb5Wc4ICDKKuAg6leBu6Q
            6ZyBTTKPa1bvtCBtm+lhlIgbZBqGHQkGN4XKN++snWQ8HZ7Bm3qR6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdjc1S2pTMDNvMVplL1FP
            L3JtOWRMWDM3WWlTT2xmalF5VE5vdnZNVDJFCnptTWdTdUxHWXlNKzNHUTZWRUxV
            VWJOWXZqdVdEQ3NvMFZnNlgrZzJnSVUKLS0tIDdha2YyTGJ2bnV6ZGMzTUwyRThT
            YzZTelVVcGNESTMrRjlKa01zZnQyUnMKtkaAtnwgYur8sOYbVo4soSOC0BR367WI
            2cpNBn86PwsPCDnRthMW0ZlARo3GuA09MRoLzk/0/AHFSJxZxE5qDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWRlNmRTUjhsaHJJQnJo
            blJ4RWxESFptekJLRXpMdWRGZmV0SnBMNVZBCm8vcklmTmc4Rnk3cjJ0ZTF6STRv
            bXFMZ0ZLZVV3M3F6L1IvNWhzcUtCa2sKLS0tIDFSY0JjWFZCczNnTWxIT3pBeTZn
            cm1PUHd4M3NyalVNY21ET21tcXZlSzAKOuX4SBpUwOlPqLmPk0aWRBD9v6rYpkd6
            KwitS4Bt107bYxX1FyE3yRe07FCjsN1IowZVTnFTft4G011DSHyEqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM1FWSURua1dCazdrSHZZ
            YTFCWFJJQmY1OWp3UjAxY3I1VklMaWJtYlcwCnArMEMzZytJRjdGMENZWWRkUTNt
            bXU4UHRKdVpIZituM21DaDdnSVpYNHMKLS0tIFk4OUxwNmtNdDdvNDZZa1ZJbFdJ
            QmZDNFdLRVpXWWREM0JvZVl0M1p1TkkK8xylPHrr4F1nYy1azVL7wYkPduIjqR3r
            wX1JetYMaGCxYMcN3l+bwx2EzOVMyWPPcCA+PNJdYWgYBPcJwJCt9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUejZvdXJQcjRkaTgzbzBn
            U2I1dTVmck0rYjlHSlZJaUxKODVLN2toREZBCmRZRXZjYm1NeXBVNS84L21ZQkk1
            NnA3MnJReUIvZnVDSkdtc2JFM1h1Nk0KLS0tIGtsbkdua3duelJ5ZStpUnZnUkgw
            cmJkeWYxRnRjTWVQdW9ObHRyb1A3dGsKvSvTOvxITZLOus6Hmt/GPufkJmwS9C2J
            K7TQS9RtGsb3dvxBCX1CDemEPNTeFe0Qlkoyhulx1UroK/TJKvsjcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-22T07:06:26Z"
    mac: ENC[AES256_GCM,data:XBM6eOER4lBw0W4K0nf2MRHbLgUJS9taYS6j1CZF39WxGyVKjYLHPfvT/qLgE9fvw3miH3a/juag1/w7Pe8o8Xt3I/j7HrZ3xT0w3U8hiMwlftxdtGIr2LYNyfXREoNG//01OjSv2fcLspxNanJqXSlh9S1mFhRoDtPOIKlhtAI=,iv:283lFCZFEPm6VtAukiiy+O6Gc/rp3mxFEELTyRa3e8M=,tag:YcNFUpAk4KaIiTJ6PqBDBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
