apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
spec:
    secretTemplates:
        - name: cloudflare-api-token-secret
          stringData:
            api-token: ENC[AES256_GCM,data:WqSG9dk70EBmuk5lite5CLVGrO/xR0Y5a92We6axPK2bFQ2x8A==,iv:3pUGK+P9Hm+ti4uxXMwmGF/USGstHPBjHX73zm6Q0ss=,tag:4J/16h93i8t+of1245jpjg==,type:str]
sops:
    age:
        - recipient: age16vnesw9pd7l556h9lmgv4lyya03xsu2akc5hukhgua8mffukmsms46665n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndW11SVJqelNLdGRLd29M
            QjBYcjEwMnpEd2I4MDJOc1l0blptT2pTS1RJClFXY25XZ0NzWWhWY0txRm1TYmVl
            OGRUUGZnMVBkcFFxLzViOGhQaDc4VkEKLS0tIG1DY2wwWXBNOUJ3QW1HeGJpcXJ2
            RUZxSVEwNGZlZllDSFNUbWF0K1RXaDgKMJNptGNDJ1pxVrg2RT1Ysnj25duiPw+g
            oSnb3g0korsm/rWKjUegL7+PcBlW9kN7LWzXbJc0hWI8PyrNMeB2Cw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cxqfxy46kp8p007857c6cnk4j2ypuc0pw04utqr58uraxn0dz3ystslpxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTWhkTWRxbEg2aDlOTE5B
            MGlpRUpkT1B2RXU4VzgrSTcweDdMUnhHQmhzCm51UUpkMFAvU2RZNXYvT1VPV1Ir
            YTduMnBMM1RnZE94NXFIbHR0V3crdEEKLS0tIFVZbmY2Vk1lWVhPRDNtRmZaYzdJ
            QmRWRVV0UndLOU9WS3hleVp2RnkzeFUK22NsEEX33k0QrYdclREVropxV4qNAvnw
            cZn1fEq6dqtkNjeKJlUz6uSV8XgOlHLPXxw46pvKpKnE6wveGkObUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye3vjfjzfpdd9eqn9qlhj0jr369h8xgdxlj0j0yplpg2xqsfna3qrm73gl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUzZTSWZ6TUpQT3kyYVlR
            YWw1NUhyVzlKZC9IWTU1ejc2WXIzNWFRZEU4CnoraVhNVFlXOEppZ0NxSDdxWmYx
            Q2kzbUpUN05qV2lST0l1UTM0eUJmcUUKLS0tIDlkMlZCV0ZCcm9Wd2RHdmFuRTV1
            Z1NTN0J2b3pKMUxiWVlpMVQrVnFiTTgKMU6EBndlT5+QiIimZMGWrqOmt+Kjg37A
            8gXvEHT7ZabEqyAyx/9SGIjKsKbo7M6iHUE+Tg6z2abl+mA+gajqlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10kuyqqdzgtefr40redrl6xnw9a3pcl2589dw63n5qlllnscxccrq8jez7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTGdnRDJwR0Z1dUFlVEZD
            M2UzR3dKZlE0Z2NhK2owYmwzRFJHUzFsUFJZCkl4TXpxUEdlUUFYYkhEYmpXdk8v
            QkkrOE1yUGF3SEROeXUzS1I3MUtIVHcKLS0tIG9YQnZqR0FBT0x1dHpxOTRZaDJv
            a29pUm0zdnp1VWUzTEwwbWRxTjRGMDAKdGDzC7S6Qt23egKDVrPdLb4sssiypnL/
            SPD9ZsfZDTaqCnn1lKt/9ZL7BgcywpmU2c5zCJQPcNMgyKZ7z4bedQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cll0t2zmt8xj5x9zuka8zknymzqd5l4ewcv79yrwe9szd06kacyq5wfwr4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YmVKOEZrVVF3SHdGT2g0
            MTAwWXN6WFFnZEVZaktEUWhIbFpaZlpHN0hnCjMyRVRaRDRxbHdYWTAydWl0c2M0
            NFR2UEpUazllUnMyVzUzb1JyU05MdWcKLS0tIG5pN0RJczNBS085alZmRThWYUJL
            SzRwRUlETmZDRldUSWRjano0NENJRjQKou6ziGTiJBSEqU9XNS36o9Okag8AzTDI
            UrXjfAmgoQQWsYjBRxteTIpLf66zuC9RkepcKW0rp87nNpQNmNap8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g93uv85j5x5l9twvg4833736vcyrca2femh7gkytq8dtnhkzgs9qyfynf0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZXJmbUlMeXN0aGpTK251
            VVZyei9abVE4d1pOMG9iM0k3MjFNYmlKN1djCjdEMm4xN21SdUtmY1FNQUtkYjlw
            blp4Q0xqZHB6QkFEbUpoWUhuWkRla0UKLS0tIDl4RGo0c0g2eE0rYmZwVnZwZUhF
            WWhUUGdBSEJJYlRqQmVaOTYvMnJ3Z28K812pFwr/GqliFh7nS9gjnUxss9JsjgNL
            fLHJL0Sc8QQDUglUtaPc0RLkAncmEJS11RYG3KEuCh3q8B2eBRVV3Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17mzyvmc2dr266c5ky90e8earmvy39awwskhk6nwfavn8vprq3gwqzhcc3e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZDRWc3M5WDFKMVB0djFp
            eW4xaFFJZkRrSkRnRjlaTS9JUzB0YVlCY2g4CnN3NTRKQ1J6cTk4bG1tU0d6RERC
            ZWR6TEtyelBXWU5pZHM1R01Dd1lFQ28KLS0tIHRVdzNhUkVwem53RUV4VHlVSkhS
            QXA3Qy9Wa3BJTlR2NElncndHOFF0R0kKcuWvLkHptE7tCLD6K+n01DN2Czymb/XE
            ATq+cLq/xGaab43J/l3wp4Kp1fXtg7jO7SqMIDoXg2eAMhzfY6B9BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T20:55:35Z"
    mac: ENC[AES256_GCM,data:eRgXFubaWy6nh/xA6TxYxmmPkPYrserQfE/OQ4i3GrfKB39R9HkaL3zWXuGS0kk75GynHYZWcyEO8nJWX3JcIHclsuIpQRWTFGFOaOANWmkUeEuStnK1gcD/wPPI24q95G5v9MqvTyf3HbCKXocqCTne3CNxEQKwkmCRQfRMxmE=,iv:keJy6jotMoQqRM9jVMx2dRdsK14ECwSg8yW+nKX87bE=,tag:o00lvA+biZ6DlRhanuI6zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
