apiVersion: v1
kind: Service
metadata:
  name: traefik-tailscale
  namespace: traefik
  annotations:
    tailscale.com/hostname: "traefik"
    hajimari.io/enable: "true"
    hajimari.io/appName: "Traefik Dashboard"
    hajimari.io/icon: "mdi:router-network"
    hajimari.io/group: "Infrastructure"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: dashboard
      port: 443
      targetPort: 8080
      protocol: TCP
