apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://github.com/paulkiernan/homelab
      targetRevision: HEAD
      path: kubernetes/argocd/apps/network/cloudflared/manifests
    - repoURL: https://cloudflare.github.io/helm-charts
      targetRevision: 0.3.2
      chart: cloudflare-tunnel
      helm:
        valuesObject:
          cloudflare:
            secretName: "cloudflared-secret"
            tunnelName: "sf_kubernetes"
            ingress:
              - hostname: "*.paulynomial.com"
                service: http://traefik.traefik.svc.cluster.local:80
          image:
            repository: cloudflare/cloudflared
            tag: 2024.4.1
          env:
            - name: TUNNEL_CREDENTIALS_FILE
              value: /etc/cloudflared/creds/credentials.json
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
